import {NextResponse} from "next/server";import {db} from "@/lib/db";

type Conn={state:"READY"|"CONNECTED_DATA_ONLY"|"CONNECTION_REQUIRED";note:string};
const specs:Record<string,{format:string;deliverables:string[];paid:boolean}>={
 "Website Homepage":{format:"Responsive homepage hero + supporting module",deliverables:["Desktop hero","Mobile hero","Headline","CTA","Supporting module copy"],paid:false},
 "WooCommerce":{format:"Responsive store merchandising",deliverables:["Landing-page copy","Product tiles","Offer callout","CTA"],paid:false},
 "Pinterest":{format:"1000×1500 Pin",deliverables:["Pin image","Pin title","Description","Destination URL","UTM tags"],paid:true},
 "TikTok":{format:"1080×1920 vertical",deliverables:["Video concept","Hook","Shot list","Caption","CTA"],paid:true},
 "Facebook / Instagram":{format:"1080×1350 feed + 1080×1920 story/reel",deliverables:["Feed creative","Story/Reel creative","Primary text","Headline","CTA"],paid:true},
 "Bing / Microsoft Ads":{format:"Responsive search / shopping",deliverables:["Headlines","Descriptions","Keywords/audience","Destination URL","UTM tags"],paid:true},
 "Walmart Marketplace":{format:"Marketplace merchandising",deliverables:["Listing promotion copy","Image guidance","Offer copy"],paid:false},
 "Walmart Connect Ads":{format:"Walmart Connect",deliverables:["Sponsored-ad copy","Product set","Bid/budget brief"],paid:true},
 "Amazon US Marketplace":{format:"Marketplace merchandising",deliverables:["Promotion copy","Merchandising brief","Product set"],paid:false},
 "Amazon Ads":{format:"Amazon Sponsored Ads",deliverables:["Sponsored-product brief","Product targets","Budget brief"],paid:true},
 "Amazon Canada Marketplace":{format:"Marketplace merchandising",deliverables:["Promotion copy","Merchandising brief","Product set"],paid:false},
 "Email":{format:"Responsive email",deliverables:["Subject","Preheader","Hero","Body copy","CTA","Product block copy"],paid:false},
};
function connection(channel:string):Conn{const env=process.env;if(channel==="Pinterest")return env.PINTEREST_ACCESS_TOKEN?{state:"CONNECTED_DATA_ONLY",note:"Pinterest credentials detected; publishing adapter still needs final API execution wiring."}:{state:"CONNECTION_REQUIRED",note:"Pinterest access token required."};if(channel==="TikTok")return env.TIKTOK_ACCESS_TOKEN?{state:"CONNECTED_DATA_ONLY",note:"TikTok credentials detected; publishing adapter still needs final execution wiring."}:{state:"CONNECTION_REQUIRED",note:"TikTok credentials required."};if(channel.includes("Walmart"))return env.WALMART_CLIENT_ID&&env.WALMART_CLIENT_SECRET?{state:"CONNECTED_DATA_ONLY",note:"Walmart Marketplace credentials detected; campaign publishing adapter pending."}:{state:"CONNECTION_REQUIRED",note:"Walmart campaign credentials required."};if(channel.includes("WooCommerce")||channel==="Website Homepage")return env.WOOCOMMERCE_CONSUMER_KEY&&env.WOOCOMMERCE_CONSUMER_SECRET?{state:"CONNECTED_DATA_ONLY",note:"WooCommerce credentials detected; homepage/store publishing adapter pending."}:{state:"CONNECTION_REQUIRED",note:"WooCommerce credentials required."};if(channel==="Email")return{state:"CONNECTION_REQUIRED",note:"Email platform connection required."};return{state:"CONNECTION_REQUIRED",note:`${channel} execution connection has not been completed yet.`}}
function channelFromTitle(title:string){return title.replace(/ campaign plan$/i,"")}
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const campaign=await db.campaign.findUnique({where:{id},include:{products:{include:{product:true}},recommendations:{include:{actions:true},orderBy:{createdAt:"asc"}}}});if(!campaign)return NextResponse.json({error:"Campaign not found"},{status:404});const assets=campaign.recommendations.filter(r=>r.title.endsWith("campaign plan")).map(r=>{const channel=channelFromTitle(r.title),draft=r.actions.find(a=>a.actionType==="CREATIVE_DRAFT"),approval=r.actions.find(a=>a.actionType==="CREATIVE_APPROVED"),schedule=r.actions.find(a=>a.actionType==="SCHEDULE_EXECUTION"),publish=r.actions.find(a=>a.actionType==="PUBLISH_EXECUTION"),conn=connection(channel),spec=specs[channel]??{format:"Channel-ready creative package",deliverables:["Creative","Copy","CTA","Tracking"],paid:false};let status="DRAFT_READY";if(approval)status="APPROVED";if(schedule?.completed)status="SCHEDULED";if(publish?.completed)status="PUBLISHED";else if(approval&&conn.state!=="READY")status="READY_CONNECTION_REQUIRED";return{recommendationId:r.id,channel,status,creative:draft?.description??"Creative brief not generated.",format:spec.format,deliverables:spec.deliverables,paid:spec.paid,connection:conn,approvedAt:approval?.createdAt??null,scheduledFor:schedule?.executionTarget??null,publishedAt:publish?.completedAt??null,result:publish?.resultSummary??null}});return NextResponse.json({campaign:{id:campaign.id,name:campaign.name,objective:campaign.objective,startDate:campaign.startDate,endDate:campaign.endDate,status:campaign.status,products:campaign.products.map(x=>({sku:x.product.sku,name:x.product.name,role:x.role}))},assets,summary:{total:assets.length,approved:assets.filter(a=>["APPROVED","READY_CONNECTION_REQUIRED","SCHEDULED","PUBLISHED"].includes(a.status)).length,scheduled:assets.filter(a=>a.status==="SCHEDULED").length,published:assets.filter(a=>a.status==="PUBLISHED").length,needsConnection:assets.filter(a=>a.status==="READY_CONNECTION_REQUIRED").length}})}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const b=await req.json(),recommendationId=String(b.recommendationId||""),operation=String(b.operation||"");const rec=await db.recommendation.findFirst({where:{id:recommendationId,campaignId:id},include:{actions:true}});if(!rec)return NextResponse.json({error:"Campaign creative not found"},{status:404});if(operation==="APPROVE"){const existing=rec.actions.find(a=>a.actionType==="CREATIVE_APPROVED");if(!existing)await db.action.create({data:{recommendationId,actionType:"CREATIVE_APPROVED",description:String(b.creative||rec.actions.find(a=>a.actionType==="CREATIVE_DRAFT")?.description||"Approved campaign creative"),executionTarget:String(b.budget??"")}});return NextResponse.json({ok:true,status:"APPROVED"})}if(operation==="SCHEDULE"){const when=String(b.scheduledFor||"");if(!when)return NextResponse.json({error:"Schedule date/time required"},{status:400});const action=rec.actions.find(a=>a.actionType==="SCHEDULE_EXECUTION");if(action)await db.action.update({where:{id:action.id},data:{executionTarget:when,completed:true,completedAt:new Date(),resultSummary:"Authorized asset scheduled in LMG Marketing execution queue."}});else await db.action.create({data:{recommendationId,actionType:"SCHEDULE_EXECUTION",description:"Schedule approved campaign creative.",executionTarget:when,completed:true,completedAt:new Date(),resultSummary:"Authorized asset scheduled in LMG Marketing execution queue."}});return NextResponse.json({ok:true,status:"SCHEDULED"})}if(operation==="MARK_PUBLISHED"){const channel=channelFromTitle(rec.title),conn=connection(channel);const existing=rec.actions.find(a=>a.actionType==="PUBLISH_EXECUTION");if(existing)await db.action.update({where:{id:existing.id},data:{completed:true,completedAt:new Date(),resultSummary:String(b.result||`Publication recorded for ${channel}.`)}});else await db.action.create({data:{recommendationId,actionType:"PUBLISH_EXECUTION",description:`Publish approved ${channel} campaign asset.`,executionTarget:channel,completed:true,completedAt:new Date(),resultSummary:String(b.result||`Publication recorded for ${channel}.`)}});return NextResponse.json({ok:true,status:"PUBLISHED",connection:conn})}return NextResponse.json({error:"Unsupported production operation"},{status:400})}