"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type ProductRow={sku:string;name:string;units:number;commerceRevenue:number;productViews:number;purchaseConversionRate:number;signal:"PROMOTE"|"FIX_CONVERSION"|"WATCH"|"INSUFFICIENT_DATA"};
type SavedCampaign={id:string;name:string;objective?:string|null;startDate:string;endDate:string;status:string;products:{product:{sku:string;name:string}}[];recommendations:{id:string;title:string;recommendation:string;actions:{actionType:string;description:string;executionTarget?:string|null;completed:boolean}[]}[]};
type ProductCollection={id:string;name:string;skus:string[]};
const COLLECTION_STORAGE_KEY="lmg-marketing-product-collections-v1";
const channelOptions=[
["WEBSITE_HOMEPAGE","Website Homepage","Feature the campaign on the Laughing Moose Gifts homepage"],
["WOOCOMMERCE","WooCommerce Store","Store landing pages, offers and onsite merchandising"],
["PINTEREST","Pinterest","Pins, boards and discovery traffic"],["TIKTOK","TikTok","Short-form creative, catalog and Shop"],["META","Facebook / Instagram","Organic, catalog and paid social"],["BING","Bing / Microsoft Ads","Search, Shopping and paid advertising"],
["WALMART_MARKETPLACE","Walmart Marketplace","Marketplace merchandising, promotions and listing support"],["WALMART_ADS","Walmart Connect Ads","Paid advertising on Walmart"],
["AMAZON_US","Amazon US Marketplace","Marketplace merchandising and promotion"],["AMAZON_ADS","Amazon Ads","Sponsored Products and other paid Amazon advertising"],["AMAZON_CA","Amazon Canada Marketplace","Marketplace merchandising and promotion"],["EMAIL","Email","Customer-list campaign"]] as const;
const today=new Date();const isoDate=(d:Date)=>d.toISOString().slice(0,10);const addDays=(d:Date,n:number)=>new Date(d.getTime()+n*86400000);const recommendedStartDate=isoDate(addDays(today,8));const recommendedEndDate=isoDate(addDays(today,22));
export default function CampaignBuilderPage(){
const[products,setProducts]=useState<ProductRow[]>([]),[campaigns,setCampaigns]=useState<SavedCampaign[]>([]),[selectedProducts,setSelectedProducts]=useState<string[]>([]),[channels,setChannels]=useState<string[]>(["WEBSITE_HOMEPAGE","PINTEREST"]),[name,setName]=useState("September Country Home Campaign"),[objective,setObjective]=useState("Increase qualified traffic and profitable sales for selected hero products."),[startDate,setStartDate]=useState(recommendedStartDate),[endDate,setEndDate]=useState(recommendedEndDate),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[searchQuery,setSearchQuery]=useState(""),[collections,setCollections]=useState<ProductCollection[]>([]),[newCollectionName,setNewCollectionName]=useState(""),[collectionMessage,setCollectionMessage]=useState(""),[editingCollectionId,setEditingCollectionId]=useState<string|null>(null),[editingCollectionName,setEditingCollectionName]=useState("");
async function refresh(){const[pr,cr]=await Promise.all([fetch("/api/intelligence/products?days=30",{cache:"no-store"}),fetch("/api/campaigns",{cache:"no-store"})]);if(pr.ok){const d=await pr.json();setProducts(d.products??[]);if(!selectedProducts.length)setSelectedProducts((d.products??[]).filter((r:ProductRow)=>r.signal==="PROMOTE").slice(0,4).map((r:ProductRow)=>r.sku));}if(cr.ok){const d=await cr.json();setCampaigns(d.campaigns??[]);}}
useEffect(()=>{void refresh();try{const s=window.localStorage.getItem(COLLECTION_STORAGE_KEY);if(s)setCollections(JSON.parse(s));}catch{setCollections([]);}},[]);
const selectedRows=useMemo(()=>products.filter(p=>selectedProducts.includes(p.sku)),[products,selectedProducts]),recommendedProducts=products.filter(p=>p.signal==="PROMOTE"),normalizedSearch=searchQuery.trim().toLowerCase(),visibleProducts=useMemo(()=>!normalizedSearch?products:products.filter(p=>p.sku.toLowerCase().includes(normalizedSearch)||p.name.toLowerCase().includes(normalizedSearch)),[products,normalizedSearch]),datesOverridden=startDate!==recommendedStartDate||endDate!==recommendedEndDate,start=new Date(`${startDate}T12:00:00`),calendar=channels.map(type=>{const offset=type==="PINTEREST"?-7:type==="EMAIL"||type==="WEBSITE_HOMEPAGE"||type==="WOOCOMMERCE"?0:type==="BING"?-5:-3;const label=channelOptions.find(([v])=>v===type)?.[1]??type;return{type,label,date:isoDate(addDays(start,offset))};}).sort((a,b)=>a.date.localeCompare(b.date)),heroNames=selectedRows.slice(0,3).map(r=>r.name).join(", ")||"selected products";
function persistCollections(n:ProductCollection[]){setCollections(n);window.localStorage.setItem(COLLECTION_STORAGE_KEY,JSON.stringify(n));}function toggleProduct(s:string){setSelectedProducts(c=>c.includes(s)?c.filter(i=>i!==s):[...c,s]);}function toggleChannel(t:string){setChannels(c=>c.includes(t)?c.filter(i=>i!==t):[...c,t]);}
function createCollection(){const n=newCollectionName.trim();if(!n)return setCollectionMessage("Enter a collection name first.");if(!selectedProducts.length)return setCollectionMessage("Select at least one product before saving a collection.");persistCollections([...collections,{id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name:n,skus:[...selectedProducts]}]);setNewCollectionName("");setCollectionMessage(`${n} saved with ${selectedProducts.length} products.`);}function startEditCollection(c:ProductCollection){setEditingCollectionId(c.id);setEditingCollectionName(c.name);setSelectedProducts(c.skus);setCollectionMessage(`Editing ${c.name}. Change the name and/or product checkboxes, then save changes.`);}function saveCollectionChanges(){const n=editingCollectionName.trim();if(!editingCollectionId||!n)return setCollectionMessage("Collection name is required.");if(!selectedProducts.length)return setCollectionMessage("A collection must contain at least one product.");persistCollections(collections.map(c=>c.id===editingCollectionId?{...c,name:n,skus:[...selectedProducts]}:c));setEditingCollectionId(null);setEditingCollectionName("");setCollectionMessage(`${n} updated.`);}function cancelEdit(){setEditingCollectionId(null);setEditingCollectionName("");setCollectionMessage("Collection edit cancelled.");}function addCollectionToCampaign(c:ProductCollection){setSelectedProducts(x=>Array.from(new Set([...x,...c.skus])));setCollectionMessage(`${c.name} added to this campaign.`);}function replaceWithCollection(c:ProductCollection){setSelectedProducts(c.skus);setCollectionMessage(`${c.name} is now the campaign product set.`);}function deleteCollection(id:string){const c=collections.find(i=>i.id===id);persistCollections(collections.filter(i=>i.id!==id));if(editingCollectionId===id)cancelEdit();setCollectionMessage(c?`${c.name} deleted.`:"Collection deleted.");}
async function createCampaign(){setSaving(true);setMessage("");try{const r=await fetch("/api/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,objective,productSkus:selectedProducts,channels,startDate,endDate})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to create campaign");setMessage("Campaign plan saved. Calendar, creative drafts, execution checkpoints and metrics review actions are now persisted.");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Unable to create campaign");}finally{setSaving(false);}}
return <main className="campaign-shell"><header className="campaign-topbar"><div><p className="eyebrow">Laughing Moose Gifts · LMG Marketing</p><p className="campaign-links"><Link href="/">Marketing Intelligence</Link> · <Link href="/diagnostics">Diagnostic Center</Link></p></div></header>
<section className="campaign-details-card"><h2 className="campaign-card-step-title">1 · Build New Marketing Campaign</h2><p className="date-recommendation-copy"><strong>Intelligence recommendation:</strong> begin {recommendedStartDate} and end {recommendedEndDate}. These dates are recommendations only and remain subject to your approval or override.</p><div className="campaign-details-grid"><label>Campaign name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Start <span className="recommendation-tag">Recommended</span><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>End <span className="recommendation-tag">Recommended</span><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div><label>Objective<textarea value={objective} onChange={e=>setObjective(e.target.value)} rows={2}/></label><div className="date-approval-row"><span className={datesOverridden?"date-status overridden":"date-status recommended"}>{datesOverridden?"Dates overridden by you":"Using Intelligence-recommended dates"}</span>{datesOverridden&&<button type="button" className="button-muted" onClick={()=>{setStartDate(recommendedStartDate);setEndDate(recommendedEndDate)}}>Restore recommended dates</button>}</div></section>
<section className="campaign-workspace"><h1 className="campaign-name-title">{name||"Untitled Campaign"}</h1><h2 className="campaign-step-title">2 · Products to Promote</h2><h3 className="campaign-section-title">Find products or use a collection</h3><p className="campaign-intro">Search by SKU, full product name, or any part of the product name. Products marked <strong>PROMOTE</strong> already convert comparatively well but need more traffic.</p><div className="campaign-divider"/><div className="promotion-columns"><section className="promotion-pane"><h3>Find individual products</h3><p className="pane-subtitle">Search and select specific products to promote.</p><label className="field-label">Search products<input type="search" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="SKU or product name — e.g. Rustic Rooster"/></label><p className="match-count"><strong>{visibleProducts.length}</strong> matching products</p><div className="product-table-wrap"><table className="campaign-table"><thead><tr><th>Use</th><th>Product</th><th>Signal</th><th>Views</th><th>Conversion</th><th>30d Revenue</th></tr></thead><tbody>{visibleProducts.map(p=><tr key={p.sku}><td><input type="checkbox" checked={selectedProducts.includes(p.sku)} onChange={()=>toggleProduct(p.sku)}/></td><td><strong>{p.name}</strong><br/><small>{p.sku}</small></td><td><span className={`signal signal-${p.signal.toLowerCase()}`}>{p.signal}</span></td><td>{p.productViews}</td><td>{(p.purchaseConversionRate*100).toFixed(1)}%</td><td>${p.commerceRevenue.toFixed(2)}</td></tr>)}</tbody></table></div></section>
<section className="promotion-pane"><h3>Collections / related product groups</h3><p className="pane-subtitle">Build, edit and reuse product families and merchandising groups.</p>{editingCollectionId?<><div className="collection-edit-box"><strong>Edit collection</strong><input value={editingCollectionName} onChange={e=>setEditingCollectionName(e.target.value)} placeholder="Collection name"/><p>The product checkboxes on the left are this collection's membership. Add or remove products there, then save.</p><div className="collection-actions"><button type="button" onClick={saveCollectionChanges}>Save changes</button><button type="button" className="text-button" onClick={cancelEdit}>Cancel</button></div></div></>:<><p>Create collections such as Rustic Rooster, Autumn Checkerboard, candles, potholders, or any hand-picked merchandising group.</p><div className="collection-create-row"><input value={newCollectionName} onChange={e=>setNewCollectionName(e.target.value)} placeholder="Collection name — e.g. Rustic Rooster"/><button type="button" className="button-outline" onClick={createCollection}>Save selected as collection</button></div></>}<button type="button" className="button-muted" onClick={()=>setSelectedProducts([])}>Clear selection</button>{collectionMessage&&<p className="status-message"><strong>{collectionMessage}</strong></p>}<h4 className="saved-heading">Saved collections</h4>{collections.length===0?<div className="collection-empty">No saved collections yet.</div>:<div className="collection-list">{collections.map(c=><article className="collection-row" key={c.id}><div><strong>{c.name}</strong><small>{c.skus.length} products</small></div><div className="collection-actions"><button type="button" onClick={()=>replaceWithCollection(c)}>Promote</button><button type="button" onClick={()=>addCollectionToCampaign(c)}>Add</button><button type="button" onClick={()=>startEditCollection(c)}>Edit</button><button type="button" className="text-button" onClick={()=>deleteCollection(c.id)}>Delete</button></div></article>)}</div>}<div className="campaign-tip">Collections can be saved, recalled, edited and deleted. Editing loads the collection's products into the selection pane.</div></section></div></section>
<section id="channels" className="campaign-stage-panel"><div className="stage-heading"><span>3</span><div><p className="eyebrow">Promotional assets & channels</p><h2>Select where this campaign should appear</h2></div></div><p>Marketplace presence and paid advertising are separate promotional assets. Select either or both where appropriate.</p><div className="channel-grid">{channelOptions.map(([type,label,detail])=><article className={`channel-card ${channels.includes(type)?"selected":""}`} key={type}><label><input type="checkbox" checked={channels.includes(type)} onChange={()=>toggleChannel(type)}/> <strong>{label}</strong></label><p>{detail}</p></article>)}</div></section>
<section className="campaign-stage-panel"><div className="stage-heading"><span>4</span><div><p className="eyebrow">Recommended calendar</p><h2>Stagger discovery before the selling window</h2></div></div><div className="calendar-list">{calendar.map(i=><p key={i.type}><strong>{i.date}</strong><span>{i.label}</span></p>)}</div></section><section className="campaign-stage-panel"><div className="stage-heading"><span>5</span><div><p className="eyebrow">Creative</p><h2>Generated creative brief</h2></div></div><p><strong>Hero products:</strong> {heroNames}</p><p><strong>Core message:</strong> Warm, useful country-home inspiration with a clear reason to shop now. Adapt the hook, body copy, image/video treatment and CTA to each selected asset.</p><p><strong>Objective:</strong> {objective}</p></section><section className="campaign-stage-panel"><div className="stage-heading"><span>6</span><div><p className="eyebrow">Schedule / execute / measure</p><h2>Create the reusable campaign workflow</h2></div></div><button className="primary-button" onClick={createCampaign} disabled={saving||!selectedProducts.length||!channels.length}>{saving?"Creating…":"Create Campaign Plan"}</button>{message&&<p className="status-message"><strong>{message}</strong></p>}</section><nav className="campaign-stepper"><span className="done">✓ Campaign Details</span><span className="active">2 Products to Promote</span><a href="#channels">3 Promotional Assets</a><span>4 Review & Launch</span><a className="next-button" href="#channels">Next: Promotional Assets →</a></nav>{campaigns.length>0&&<section className="campaign-history"><h2>Saved campaign workflows</h2>{campaigns.map(c=><details key={c.id}><summary>{c.name} · {c.status}</summary><p>{c.startDate.slice(0,10)} → {c.endDate.slice(0,10)} · {c.products.length} products · {c.recommendations.length} channel plans</p></details>)}</section>}</main>;
}