"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import LmgTopNav from "@/components/LmgTopNav";
import {campaignChannels} from "@/lib/campaign-channels";

type Product={sku:string;name:string;price?:number|null;stock?:number|null;imageUrl?:string|null;signal:string};
type Campaign={id:string;name:string;objective?:string|null;offer?:string|null;status:string;workflowStage?:string;startDate:string;endDate:string;channels?:string[];products:{product:{sku:string;name:string}}[];contentAssets?:Array<{approvalStatus:string;publicationStatus:string}>};
const draftKey="lmg-campaign-operations-draft-v1";
const date=(offset:number)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)};
const stages=["Campaign Definition","Product and Channel Selection","ChatGPT Campaign Brief","Approved Content Import","Review and Approval","Scheduling and Execution","Performance Measurement","Campaign Closeout"];

export default function CampaignOperations(){
 const[products,setProducts]=useState<Product[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[name,setName]=useState(""),[objective,setObjective]=useState(""),[offer,setOffer]=useState(""),[budget,setBudget]=useState("0"),[startDate,setStartDate]=useState(date(7)),[endDate,setEndDate]=useState(date(28)),[selected,setSelected]=useState<string[]>([]),[channels,setChannels]=useState<string[]>(["WOOCOMMERCE","PINTEREST"]),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false);
 async function load(){const[p,c]=await Promise.all([fetch("/api/intelligence/products?days=90",{cache:"no-store"}),fetch("/api/campaigns",{cache:"no-store"})]);if(p.ok)setProducts((await p.json()).products??[]);if(c.ok)setCampaigns((await c.json()).campaigns??[])}
 useEffect(()=>{void load();try{const saved=JSON.parse(localStorage.getItem(draftKey)||"null");if(saved){setName(saved.name||"");setObjective(saved.objective||"");setOffer(saved.offer||"");setBudget(String(saved.budget??0));setStartDate(saved.startDate||date(7));setEndDate(saved.endDate||date(28));setSelected(saved.selected||[]);setChannels(saved.channels||["WOOCOMMERCE","PINTEREST"])}}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify({name,objective,offer,budget,startDate,endDate,selected,channels}))}catch{}},[name,objective,offer,budget,startDate,endDate,selected,channels]);
 const chosen=useMemo(()=>products.filter(p=>selected.includes(p.sku)),[products,selected]);
 const toggle=(list:string[],value:string,setter:(next:string[])=>void)=>setter(list.includes(value)?list.filter(item=>item!==value):[...list,value]);
 async function save(){setNotice("");if(!name.trim()||!objective.trim()||!selected.length||!channels.length)return setNotice("Enter a campaign name and objective, then select at least one product and channel.");setSaving(true);try{const response=await fetch("/api/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,objective,offer,budget:Number(budget||0),startDate,endDate,productSkus:selected,channels})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Campaign draft could not be saved.");localStorage.removeItem(draftKey);setNotice("Campaign draft saved. The ChatGPT brief is ready for review.");await load();if(body.campaign?.id)window.location.href=`/campaigns/${body.campaign.id}/brief`;}catch(error){setNotice(error instanceof Error?error.message:"Campaign draft could not be saved.")}finally{setSaving(false)}}
 return <main className="ops-shell"><LmgTopNav active="/campaigns"/><header className="ops-hero"><p className="eyebrow">Campaign operations</p><h1>Plan, approve, publish, and measure campaigns</h1><p>ChatGPT creates and interprets. LMG Marketing supplies facts, controls approval, executes supported channels, and preserves the audit trail.</p><div className="trace-sequence">Data → Campaign Brief → ChatGPT Content → Approval → Schedule → Publication → Measurement → ChatGPT Diagnosis → Decision → Action → Result</div></header>
 <ol className="workflow-stages">{stages.map((stage,index)=><li key={stage}><span>{index+1}</span>{stage}</li>)}</ol>
 <section className="ops-panel"><p className="eyebrow">1 · Campaign Definition</p><div className="ops-fields"><label>Campaign name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Fall Country Home Campaign"/></label><label>Objective<textarea value={objective} onChange={e=>setObjective(e.target.value)} rows={3}/></label><label>Offer<textarea value={offer} onChange={e=>setOffer(e.target.value)} rows={3} placeholder="Offer, constraints, exclusions, and urgency"/></label><label>Budget<input type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)}/></label><label>Start<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>End<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div></section>
 <section className="ops-panel"><p className="eyebrow">2 · Product and Channel Selection</p><h2>Products ({selected.length})</h2><div className="ops-product-grid">{products.map(product=><label className={selected.includes(product.sku)?"selected":""} key={product.sku}><input type="checkbox" checked={selected.includes(product.sku)} onChange={()=>toggle(selected,product.sku,setSelected)}/>{product.imageUrl&&<img src={product.imageUrl} alt=""/>}<span><strong>{product.name}</strong><small>{product.sku} · {product.price==null?"price unavailable":`$${Number(product.price).toFixed(2)}`} · {product.stock==null?"stock unavailable":`${product.stock} in stock`}</small></span></label>)}</div><h2>Channels</h2><div className="ops-channel-grid">{Object.entries(campaignChannels).map(([code,channel])=><label className={channels.includes(code)?"selected":""} key={code}><input type="checkbox" checked={channels.includes(code)} onChange={()=>toggle(channels,code,setChannels)}/><span><strong>{channel.label}</strong><small>{channel.execution.replaceAll("_"," ")}</small><em>{channel.deliverables.join(" · ")}</em></span></label>)}</div><div className="ops-selection-summary"><strong>{chosen.map(p=>p.name).join(", ")||"No products selected"}</strong><span>{channels.join(", ")||"No channels selected"}</span></div><button className="ops-primary" disabled={saving} onClick={save}>{saving?"Saving…":"Save Draft & Build ChatGPT Brief"}</button>{notice&&<p className="ops-notice">{notice}</p>}</section>
 <section className="ops-panel"><p className="eyebrow">Existing campaign operations</p><h2>Continue a campaign</h2><div className="ops-campaign-list">{campaigns.map(c=><article key={c.id}><div><span>{c.status} · {c.workflowStage||"LEGACY"}</span><h3>{c.name}</h3><p>{c.objective}</p><small>{c.products.length} products · {Array.isArray(c.channels)?c.channels.join(", "):"Legacy channel record"}</small></div><nav><Link href={`/campaigns/${c.id}/brief`}>Brief</Link><Link href={`/campaigns/${c.id}/content`}>Content</Link><Link href={`/campaigns/diagnostics?campaign=${c.id}`}>Performance</Link><Link href="/campaigns/calendar">Calendar</Link></nav></article>)}</div></section></main>;
}
