export type CampaignTemplate = {
  id: string;
  name: string;
  purpose: string;
  objective: string;
  durationDays: number;
  recommendedAssets: string[];
  optionalAssets: string[];
  headlineTemplate: string;
  messageTemplate: string;
  ctaTemplate: string;
  measures: string[];
};

// Templates intentionally describe the full desired promotional mix even when a
// channel connector is not implemented yet. Execution readiness is a separate
// concern from campaign strategy and can be completed connector-by-connector.
export const campaignTemplates: CampaignTemplate[] = [
  {id:"PRODUCT_LAUNCH",name:"Product / Collection Launch",purpose:"Introduce a new product or collection and build initial awareness and sales velocity.",objective:"Launch [PRODUCT/COLLECTION] with coordinated awareness, traffic and conversion activity.",durationDays:21,recommendedAssets:["WEBSITE_HOMEPAGE","WOOCOMMERCE","PINTEREST","EMAIL","META","TIKTOK","BING","WALMART_MARKETPLACE","WALMART_ADS","AMAZON_US","AMAZON_ADS","AMAZON_CA"],optionalAssets:[],headlineTemplate:"Introducing [PRODUCT/COLLECTION]",messageTemplate:"Meet [PRODUCT/COLLECTION], a new [CATEGORY] created for [CUSTOMER BENEFIT]. Discover [KEY FEATURE/REASON TO BUY] and shop through [END DATE].",ctaTemplate:"Discover [PRODUCT/COLLECTION]",measures:["Qualified traffic","Conversion rate","Revenue","Units sold","New-customer rate"]},
  {id:"SEASONAL",name:"Seasonal Campaign",purpose:"Capture seasonal demand with coordinated merchandising and discovery.",objective:"Generate seasonal demand for [SEASON] products and collections during the highest-opportunity selling window.",durationDays:35,recommendedAssets:["WEBSITE_HOMEPAGE","WOOCOMMERCE","PINTEREST","EMAIL","META","TIKTOK","BING","WALMART_MARKETPLACE","WALMART_ADS","AMAZON_US","AMAZON_ADS","AMAZON_CA"],optionalAssets:[],headlineTemplate:"Bring [SEASON] Home",messageTemplate:"Welcome [SEASON] with [PRODUCT/COLLECTION]. Add [MOOD/BENEFIT] to your home with pieces selected for [SEASONAL OCCASION].",ctaTemplate:"Shop the [SEASON] Collection",measures:["Seasonal revenue","Traffic","Conversion rate","Channel contribution","ROAS"]},
  {id:"PROMOTIONAL_EVENT",name:"Sale / Promotional Event",purpose:"Create urgency and immediate purchase activity around a defined offer.",objective:"Increase short-term sales using [OFFER] on [PRODUCTS/COLLECTION] through [END DATE].",durationDays:10,recommendedAssets:["WEBSITE_HOMEPAGE","WOOCOMMERCE","EMAIL","PINTEREST","META","TIKTOK","BING","WALMART_MARKETPLACE","WALMART_ADS","AMAZON_US","AMAZON_ADS","AMAZON_CA"],optionalAssets:[],headlineTemplate:"[OFFER] on [PRODUCT/COLLECTION]",messageTemplate:"For a limited time, enjoy [OFFER] on [PRODUCT/COLLECTION]. Shop before [END DATE] while [AVAILABILITY/TERMS].",ctaTemplate:"Shop the Offer",measures:["Incremental revenue","Conversion lift","Units sold","Discount cost","ROAS"]},
  {id:"EVERGREEN_SPOTLIGHT",name:"Product Spotlight / Evergreen",purpose:"Give a proven or strategically important product additional qualified exposure.",objective:"Increase qualified traffic and profitable sales for [PRODUCT] using its strongest customer benefit.",durationDays:21,recommendedAssets:["WEBSITE_HOMEPAGE","WOOCOMMERCE","PINTEREST","EMAIL","META","TIKTOK","BING","WALMART_MARKETPLACE","WALMART_ADS","AMAZON_US","AMAZON_ADS","AMAZON_CA"],optionalAssets:[],headlineTemplate:"Why You'll Love [PRODUCT]",messageTemplate:"Meet [PRODUCT]: [PRIMARY BENEFIT]. It's a natural fit for [USE CASE] thanks to [FEATURE/PROOF].",ctaTemplate:"Shop [PRODUCT]",measures:["Product views","CTR","Conversion rate","Revenue","Revenue per visitor"]},
  {id:"COLLECTION_THEME",name:"Collection / Theme Campaign",purpose:"Merchandise related products together as one coordinated story or look.",objective:"Grow basket-building and discovery around the [THEME/COLLECTION] product family.",durationDays:28,recommendedAssets:["WEBSITE_HOMEPAGE","WOOCOMMERCE","PINTEREST","EMAIL","META","TIKTOK","BING","WALMART_MARKETPLACE","WALMART_ADS","AMAZON_US","AMAZON_ADS","AMAZON_CA"],optionalAssets:[],headlineTemplate:"Create the [THEME] Look",messageTemplate:"Bring together [PRODUCT GROUP] for a coordinated [THEME] look. Start with [HERO PRODUCT] and complete it with [SUPPORTING PRODUCTS].",ctaTemplate:"Explore [COLLECTION]",measures:["Collection revenue","Products per order","Cross-sell rate","Traffic","Conversion rate"]},
  {id:"INVENTORY_CLEARANCE",name:"Inventory / Clearance",purpose:"Move excess, aging or strategically selected inventory while protecting margin.",objective:"Reduce inventory in [PRODUCT/SKU GROUP] from [CURRENT LEVEL] toward [TARGET LEVEL] by [END DATE].",durationDays:14,recommendedAssets:["WEBSITE_HOMEPAGE","WOOCOMMERCE","EMAIL","PINTEREST","META","TIKTOK","BING","WALMART_MARKETPLACE","WALMART_ADS","AMAZON_US","AMAZON_ADS","AMAZON_CA"],optionalAssets:[],headlineTemplate:"Limited Quantities: [PRODUCT/COLLECTION]",messageTemplate:"We're making room for what's next. Save [OFFER] on [PRODUCT/COLLECTION] while remaining quantities last.",ctaTemplate:"Shop Before It's Gone",measures:["Units liquidated","Inventory reduction","Margin retained","Revenue","Sell-through rate"]},
  {id:"MARKETPLACE_GROWTH",name:"Marketplace Growth",purpose:"Increase marketplace visibility, velocity and profitable sales on Amazon or Walmart.",objective:"Improve [MARKETPLACE] performance for [PRODUCT/SKU GROUP] through coordinated listing, promotion and advertising activity.",durationDays:28,recommendedAssets:["WALMART_MARKETPLACE","WALMART_ADS","AMAZON_US","AMAZON_ADS","AMAZON_CA","WEBSITE_HOMEPAGE","WOOCOMMERCE","PINTEREST","EMAIL","META","TIKTOK","BING"],optionalAssets:[],headlineTemplate:"Grow [PRODUCT] on [MARKETPLACE]",messageTemplate:"Increase qualified marketplace exposure for [PRODUCT] by improving [LISTING/OFFER/TRAFFIC DRIVER] and supporting it with [PROMOTIONAL ASSET].",ctaTemplate:"Shop on [MARKETPLACE]",measures:["Marketplace impressions","CTR","Conversion rate","Units","ROAS","Organic rank/velocity"]},
  {id:"REENGAGEMENT",name:"Customer Re-engagement",purpose:"Bring previous customers and interested visitors back with relevant products or offers.",objective:"Re-engage [AUDIENCE SEGMENT] with [PRODUCT/COLLECTION/OFFER] and generate repeat visits and purchases.",durationDays:10,recommendedAssets:["EMAIL","WEBSITE_HOMEPAGE","WOOCOMMERCE","PINTEREST","META","TIKTOK","BING","WALMART_MARKETPLACE","WALMART_ADS","AMAZON_US","AMAZON_ADS","AMAZON_CA"],optionalAssets:[],headlineTemplate:"Come Back to [PRODUCT/COLLECTION]",messageTemplate:"It's a great time to take another look at [PRODUCT/COLLECTION]. [NEW REASON/OFFER/SEASONAL HOOK] makes now a good time to return.",ctaTemplate:"Take Another Look",measures:["Open rate","CTR","Return visits","Repeat conversion","Revenue per recipient"]}
];