const site=(process.env.WOOCOMMERCE_URL||"https://laughingmoosegifts.com").replace(/\/$/,"");
const username=process.env.WORDPRESS_USERNAME||"";
const appPassword=(process.env.WORDPRESS_APPLICATION_PASSWORD||"").replace(/\s+/g,"");
function auth(){return `Basic ${Buffer.from(`${username}:${appPassword}`).toString("base64")}`;}
async function wp(path:string,init:RequestInit={}){if(!username||!appPassword)throw new Error("WordPress credentials are not configured");const r=await fetch(`${site}/wp-json${path}`,{...init,headers:{Authorization:auth(),Accept:"application/json",...(init.headers||{})},cache:"no-store"});const text=await r.text();let body:any;try{body=JSON.parse(text)}catch{body=text}if(!r.ok)throw new Error(`WordPress ${r.status}: ${typeof body==="string"?body.slice(0,300):body?.message||"request failed"}`);return body;}
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
export type HomepageHeroCreative={headline:string;body:string;cta:string;destinationUrl:string;imageUrl:string};
export type HomepageSnapshot={pageId:number;coverIndex:number;coverRaw:string;capturedAt:string};
function coverMatches(raw:string){const re=/<!--\s+wp:cover(?:\s+({[^>]*}))?\s*-->([\s\S]*?)<!--\s+\/wp:cover\s*-->/g;return[...raw.matchAll(re)]}
function chooseHeroIndex(raw:string){const configured=Number(process.env.WORDPRESS_HERO_COVER_INDEX??"0"),matches=coverMatches(raw);if(!matches.length)throw new Error("No Gutenberg Cover block exists on the configured homepage");if(Number.isInteger(configured)&&configured>=0&&configured<matches.length)return configured;return 0}
export async function getHomepage(){const settings=await wp("/wp/v2/settings"),pageId=Number(settings?.page_on_front||0);if(!pageId)throw new Error("WordPress has no static front page configured");const page=await wp(`/wp/v2/pages/${pageId}?context=edit`);return{pageId,page,raw:String(page?.content?.raw||"")}}
export async function captureHomepageHero():Promise<HomepageSnapshot>{const{pageId,raw}=await getHomepage(),matches=coverMatches(raw),coverIndex=chooseHeroIndex(raw),m=matches[coverIndex];if(!m)throw new Error("Configured homepage hero Cover block was not found");return{pageId,coverIndex,coverRaw:m[0],capturedAt:new Date().toISOString()}}
async function ensureMedia(imageUrl:string){if(!/^https?:\/\//i.test(imageUrl))throw new Error("Hero image URL must be an http(s) URL");if(imageUrl.startsWith(site+"/"))return{url:imageUrl,id:undefined as number|undefined};const src=await fetch(imageUrl,{cache:"no-store"});if(!src.ok)throw new Error(`Unable to retrieve campaign image (${src.status})`);const buf=Buffer.from(await src.arrayBuffer()),contentType=src.headers.get("content-type")||"image/jpeg",ext=contentType.includes("png")?"png":contentType.includes("webp")?"webp":"jpg",filename=`lmg-campaign-hero-${Date.now()}.${ext}`;const media=await wp("/wp/v2/media",{method:"POST",headers:{"Content-Type":contentType,"Content-Disposition":`attachment; filename=\"${filename}\"`},body:buf});return{id:Number(media.id),url:String(media.source_url||media.guid?.rendered||imageUrl)}}
function rewriteHeroCover(coverRaw:string,creative:HomepageHeroCreative,media:{id?:number;url:string}){let out=coverRaw;out=out.replace(/<!--\s+wp:cover(?:\s+({[^>]*}))?\s*-->/,(full,json)=>{let attrs:any={};try{attrs=json?JSON.parse(json):{}}catch{}attrs.url=media.url;if(media.id)attrs.id=media.id;return `<!-- wp:cover ${JSON.stringify(attrs)} -->`});out=out.replace(/(<img\b[^>]*\bsrc=["'])[^"']*(["'][^>]*>)/i,`$1${media.url}$2`);if(media.id)out=out.replace(/wp-image-\d+/i,`wp-image-${media.id}`);const headline=esc(creative.headline),body=esc(creative.body),cta=esc(creative.cta),href=esc(creative.destinationUrl);out=out.replace(/(<h[1-6][^>]*>)[\s\S]*?(<\/h[1-6]>)/i,`$1${headline}$2`);out=out.replace(/(<p(?![^>]*wp-block-button__link)[^>]*>)[\s\S]*?(<\/p>)/i,`$1${body}$2`);out=out.replace(/(<a\b[^>]*class=["'][^"']*wp-block-button__link[^"']*["'][^>]*href=["'])[^"']*(["'][^>]*>)[\s\S]*?(<\/a>)/i,`$1${href}$2${cta}$3`);const inner=/^(<!--\s+wp:cover[^>]*-->)([\s\S]*)(<!--\s+\/wp:cover\s*-->)$/.exec(out);if(inner&&!inner[2].includes("lmg-hero-click-target")){out=`${inner[1]}<!-- wp:html --><a class="lmg-hero-click-target" href="${href}" aria-label="${headline}" style="position:absolute;inset:0;z-index:1" tabindex="-1"></a><!-- /wp:html -->${inner[2]}${inner[3]}`;out=out.replace(/class=(["'])wp-block-cover__inner-container\1/i,`class=$1wp-block-cover__inner-container$1 style=$1position:relative;z-index:2;pointer-events:none$1`).replace(/class=(["'])([^"']*wp-block-button__link[^"']*)\1/i,`class=$1$2$1 style=$1pointer-events:auto;position:relative;z-index:3$1`)}return out}
export async function publishHomepageHero(creative:HomepageHeroCreative){if(!creative.headline.trim()||!creative.cta.trim()||!creative.destinationUrl.trim()||!creative.imageUrl.trim())throw new Error("Headline, CTA, destination URL, and image are required");const destination=new URL(creative.destinationUrl);if(!["http:","https:"].includes(destination.protocol))throw new Error("Destination URL must be http(s)");const{pageId,raw}=await getHomepage(),matches=coverMatches(raw),coverIndex=chooseHeroIndex(raw),target=matches[coverIndex];if(!target)throw new Error("Homepage hero Cover block was not found");const media=await ensureMedia(creative.imageUrl),replacement=rewriteHeroCover(target[0],creative,media),next=raw.slice(0,target.index!)+replacement+raw.slice(target.index!+target[0].length);await wp(`/wp/v2/pages/${pageId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:next,status:"publish"})});const verify=await wp(`/wp/v2/pages/${pageId}?context=edit`),verifyRaw=String(verify?.content?.raw||"");if(!verifyRaw.includes(creative.headline)||!verifyRaw.includes(media.url)||!verifyRaw.includes(creative.destinationUrl))throw new Error("WordPress update returned success but hero verification failed");return{pageId,coverIndex,mediaId:media.id,imageUrl:media.url,verified:true,publishedAt:new Date().toISOString(),previousCoverRaw:target[0]}}
export async function restoreHomepageHero(snapshot:HomepageSnapshot){const{pageId,raw}=await getHomepage();if(pageId!==snapshot.pageId)throw new Error("Homepage changed since this campaign was scheduled; refusing automatic restore");const matches=coverMatches(raw),current=matches[snapshot.coverIndex];if(!current)throw new Error("Homepage hero slot no longer exists; refusing automatic restore");const next=raw.slice(0,current.index!)+snapshot.coverRaw+raw.slice(current.index!+current[0].length);await wp(`/wp/v2/pages/${pageId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:next,status:"publish"})});return{pageId,restored:true,restoredAt:new Date().toISOString()}}
