const site=(process.env.WOOCOMMERCE_URL||"https://laughingmoosegifts.com").replace(/\/$/,"");
const username=process.env.WORDPRESS_USERNAME||"";
const appPassword=(process.env.WORDPRESS_APPLICATION_PASSWORD||"").replace(/\s+/g,"");
function auth(){return `Basic ${Buffer.from(`${username}:${appPassword}`).toString("base64")}`}
async function wp(path:string,init:RequestInit={}){if(!username||!appPassword)throw new Error("WordPress credentials are not configured");const r=await fetch(`${site}/wp-json${path}`,{...init,headers:{Authorization:auth(),Accept:"application/json",...(init.headers||{})},cache:"no-store"});const text=await r.text();let body:any;try{body=JSON.parse(text)}catch{body=text}if(!r.ok)throw new Error(`WordPress ${r.status}: ${typeof body==="string"?body.slice(0,300):body?.message||"request failed"}`);return body}
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function slugify(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)}

export type CampaignPageTarget={campaignId:string;campaignName:string;opportunityId:"landing-page"|"collection-page";headline:string;body:string;cta:string;imageUrl:string;productSkus:string[];startAt:string;endAt:string};

export async function uploadCampaignImage(buffer:Buffer,campaignName:string,opportunityId:string){const filename=`${slugify(campaignName)}-${opportunityId}-${Date.now()}.jpg`;const bytes=Uint8Array.from(buffer);const media=await wp("/wp/v2/media",{method:"POST",headers:{"Content-Type":"image/jpeg","Content-Disposition":`attachment; filename=\"${filename}\"`},body:bytes});return{id:Number(media.id),url:String(media.source_url||media.guid?.rendered||"")}}
async function upsertPage(slug:string,title:string,content:string){const found=await wp(`/wp/v2/pages?slug=${encodeURIComponent(slug)}&context=edit`);const existing=Array.isArray(found)?found[0]:null;const payload={title,slug,content,status:"publish"};if(existing?.id){const page=await wp(`/wp/v2/pages/${existing.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});return{id:Number(page.id),url:String(page.link||`${site}/${slug}/`),created:false}}const page=await wp("/wp/v2/pages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});return{id:Number(page.id),url:String(page.link||`${site}/${slug}/`),created:true}}

export async function publishCampaignLandingPage(target:CampaignPageTarget){const slug=`campaign-${slugify(target.campaignName)}`;const products=target.productSkus.length?`<!-- wp:shortcode -->[products skus="${target.productSkus.map(esc).join(",")}" columns="3" orderby="post__in"]<!-- /wp:shortcode -->`:"";const content=`<!-- wp:cover {"url":"${esc(target.imageUrl)}","dimRatio":20,"minHeight":520,"minHeightUnit":"px","contentPosition":"center center"} --><div class="wp-block-cover" style="min-height:520px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-20 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="${esc(target.imageUrl)}" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":1} --><h1>${esc(target.headline)}</h1><!-- /wp:heading --><!-- wp:paragraph --><p>${esc(target.body)}</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#shop-campaign">${esc(target.cta)}</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div></div><!-- /wp:cover --><!-- wp:group {"anchor":"shop-campaign"} --><div class="wp-block-group" id="shop-campaign"><!-- wp:heading --><h2>Shop the Campaign</h2><!-- /wp:heading -->${products}</div><!-- /wp:group -->`;const page=await upsertPage(slug,target.headline,content);return{...page,publishedAt:new Date().toISOString(),slug}}

export async function publishCampaignCollectionPage(target:CampaignPageTarget){const slug=`collection-${slugify(target.campaignName)}`;const products=`<!-- wp:shortcode -->[products skus="${target.productSkus.map(esc).join(",")}" columns="4" orderby="post__in"]<!-- /wp:shortcode -->`;const content=`<!-- wp:image {"sizeSlug":"full"} --><figure class="wp-block-image size-full"><img src="${esc(target.imageUrl)}" alt="${esc(target.campaignName)} collection"/></figure><!-- /wp:image --><!-- wp:heading {"level":1} --><h1>${esc(target.headline)}</h1><!-- /wp:heading --><!-- wp:paragraph --><p>${esc(target.body)}</p><!-- /wp:paragraph -->${products}`;const page=await upsertPage(slug,target.headline,content);return{...page,publishedAt:new Date().toISOString(),slug}}

export async function unpublishCampaignPage(pageId:number){const page=await wp(`/wp/v2/pages/${pageId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"draft"})});return{pageId,status:String(page.status||"draft"),unpublishedAt:new Date().toISOString()}}
