"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Action={id:string;actionType:string;description:string;executionTarget?:string|null;completed?:boolean;resultSummary?:string|null};
type Recommendation={id:string;title:string;status:string;actions:Action[]};
type Campaign={id:string;name:string;objective?:string|null;startDate:string;endDate:string;status:string;createdAt?:string;products:{product:{sku:string;name:string}}[];recommendations:Recommendation[]};
type CampaignInstance=Campaign&{sourceIds:string[];actions:Action[]};
const phaseOrder=["CALENDAR","CREATIVE_DRAFT","SCHEDULE_EXECUTION","METRICS_REVIEW"] as const;
const actionLabel:Record<string,string>={CALENDAR:"Calendar",CREATIVE_DRAFT:"Creative",SCHEDULE_EXECUTION:"Schedule / Execute",METRICS_REVIEW:"Measurement"};
function instanceKey(c:Campaign){const skus=c.products.map(p=>p.product.sku).sort().join(",");return[c.name.trim().toLowerCase(),c.startDate.slice(0,10),skus].join("|")}
function actionKey(a:Action){return[a.actionType,a.executionTarget??"",a.description].join("|")}
function parseTarget(a:Action){try{return a.executionTarget?JSON.parse(a.executionTarget):null}catch{return null}}
function opportunityFor(a:Action){if(a.actionType==="WORDPRESS_HOMEPAGE_HERO")return{id:"homepage-hero",label:"Homepage Hero",channel:"WooCommerce / Website"};if(a.actionType==="WORDPRESS_CAMPAIGN_LANDING_PAGE")return{id:"landing-page",label:"Dedicated Campaign Landing Page",channel:"WooCommerce / Website"};if(a.actionType==="WORDPRESS_CAMPAIGN_COLLECTION_PAGE")return{id:"collection-page",label:"Campaign Collection Page",channel:"WooCommerce / Website"};const t=parseTarget(a);if(t?.opportunityId==="homepage-hero")return{id:t.opportunityId,label:"Homepage Hero",channel:"WooCommerce / Website"};if(t?.opportunityId==="landing-page")return{id:t.opportunityId,label:"Dedicated Campaign Landing Page",channel:"WooCommerce / Website"};if(t?.opportunityId==="collection-page")return{id:t.opportunityId,label:"Campaign Collection Page",channel:"WooCommerce / Website"};return null}
function actionState(a:Action){let r:any={};try{r=a.resultSummary?JSON.parse(a.resultSummary):{}}catch{}if(r.error)return"NEEDS ATTENTION";if(a.actionType==="WORDPRESS_HOMEPAGE_HERO"){if(a.completed&&r.restoredAt)return"COMPLETED";if(r.publishedAt)return"LIVE";return"SCHEDULED"}if(a.actionType==="WORDPRESS_CAMPAIGN_LANDING_PAGE"||a.actionType==="WORDPRESS_CAMPAIGN_COLLECTION_PAGE"){if(a.completed&&r.unpublishedAt)return"COMPLETED";if(r.publishedAt)return"LIVE";return"SCHEDULED"}return a.completed?"COMPLETED":"SCHEDULED"}

export default function CampaignExecutionPage(){
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[stopping,setStopping]=useState<string|null>(null),[notice,setNotice]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/campaigns",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load campaigns");setCampaigns(d.campaigns??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load campaigns")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function stopCampaign(c:CampaignInstance){if(!window.confirm(`EMERGENCY STOP ${c.name}?\n\nThis will cancel remaining scheduled work and immediately withdraw any live campaign website opportunities.`))return;setStopping(c.id);setNotice("");try{const r=await fetch(`/api/campaigns/${c.id}/stop`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to stop campaign");setNotice(`${c.name} stopped. ${d.outcomes?.join(" ")||"Remaining execution cancelled."}`);await load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to stop campaign")}finally{setStopping(null)}}
 const instances=useMemo(()=>{const grouped=new Map<string,CampaignInstance>();for(const c of campaigns){const key=instanceKey(c),currentActions=c.recommendations.flatMap(r=>r.actions??[]),existing=grouped.get(key);if(!existing){grouped.set(key,{...c,sourceIds:[c.id],actions:currentActions});continue}const base=(c.createdAt??"")>=(existing.createdAt??"")?c:existing,merged=[...existing.actions,...currentActions].filter((a,i,all)=>all.findIndex(x=>actionKey(x)===actionKey(a))===i);grouped.set(key,{...base,sourceIds:[...existing.sourceIds,c.id],actions:merged})}return[...grouped.values()].sort((a,b)=>(b.createdAt??"").localeCompare(a.createdAt??""))},[campaigns]);
 const summary=useMemo(()=>({total:instances.length,scheduled:instances.filter(c=>c.status!=="PAUSED"&&c.status!=="COMPLETED").length,stopped:instances.filter(c=>c.status==="PAUSED").length}),[instances]);
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"34px 22px 60px",fontFamily:"Arial, sans-serif"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",flexWrap:"wrap"}}><div><p style={{margin:0,fontSize:12,fontWeight:800,letterSpacing:".12em",textTransform:"uppercase",color:"#6b7280"}}>LMG Marketing · Campaign Operations</p><h1 style={{fontSize:34,margin:"8px 0"}}>Campaign Execution</h1><p style={{maxWidth:800,margin:0,color:"#4b5563",lineHeight:1.55}}>Approved campaigns execute automatically on their schedule. Each campaign card identifies the individual promotional opportunities being executed.</p></div><div style={{display:"flex",gap:10}}><Link href="/campaigns" style={linkStyle}>Back to Builder</Link><button onClick={()=>void load()} style={darkButton}>Refresh status</button></div></div>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,margin:"26px 0"}}><Stat label="Campaigns" value={summary.total}/><Stat label="Scheduled / Active" value={summary.scheduled}/><Stat label="Stopped" value={summary.stopped}/><Stat label="Workflow" value="Scheduled → Live → Completed" small/></section>
  {notice&&<div style={noticeStyle}>{notice}</div>}{loading&&<div style={noticeStyle}>Loading execution state…</div>}{error&&<div style={{...noticeStyle,borderColor:"#fecaca",background:"#fef2f2",color:"#991b1b"}}>{error}</div>}
  <section style={{display:"grid",gap:18}}>{instances.map(c=>{const stopped=c.status==="PAUSED";const opportunityActions=c.actions.filter(a=>opportunityFor(a));const opportunities=[...new Map(opportunityActions.map(a=>{const o=opportunityFor(a)!;return[o.id,{...o,action:a}]})).values()];return <article key={instanceKey(c)} style={{border:"1px solid #e5e7eb",borderRadius:14,padding:20,background:"white"}}><div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"flex-start",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 6px",fontSize:22}}>{c.name}</h2><div style={{fontSize:13,color:"#6b7280"}}>{new Date(c.startDate).toLocaleDateString()} – {new Date(c.endDate).toLocaleDateString()} · {c.products.length} product{c.products.length===1?"":"s"}</div></div><div style={{display:"flex",gap:10,alignItems:"center"}}><span style={{padding:"6px 10px",borderRadius:999,fontSize:12,fontWeight:800,background:stopped?"#fee2e2":"#ecfdf5",color:stopped?"#991b1b":"#065f46"}}>{stopped?"STOPPED":"SCHEDULED"}</span>{!stopped&&c.status!=="COMPLETED"&&<button onClick={()=>void stopCampaign(c)} disabled={stopping===c.id} style={{padding:"11px 16px",border:"2px solid #991b1b",borderRadius:9,background:"#dc2626",color:"white",fontWeight:900,cursor:"pointer"}}>{stopping===c.id?"STOPPING…":"STOP CAMPAIGN"}</button>}</div></div>
  {c.objective&&<p style={{color:"#374151",lineHeight:1.5}}>{c.objective}</p>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{c.products.map(p=><span key={p.product.sku} style={{fontSize:12,padding:"5px 8px",background:"#f3f4f6",borderRadius:7}}>{p.product.name} · {p.product.sku}</span>)}</div>
  <div style={{marginBottom:16}}><div style={{fontSize:12,fontWeight:900,letterSpacing:".08em",textTransform:"uppercase",color:"#6b7280",marginBottom:8}}>Opportunities in this campaign</div>{opportunities.length?<div style={{display:"grid",gap:8}}>{opportunities.map(o=><div key={o.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,border:"1px solid #dbeafe",background:"#eff6ff",borderRadius:10,padding:"11px 13px"}}><div><strong>{o.label}</strong><div style={{fontSize:12,color:"#6b7280",marginTop:3}}>{o.channel}</div></div><span style={{fontSize:12,fontWeight:900,color:actionState(o.action)==="NEEDS ATTENTION"?"#991b1b":"#065f46"}}>{actionState(o.action)}</span></div>)}</div>:<div style={{fontSize:13,color:"#92400e",background:"#fffbeb",border:"1px solid #fde68a",padding:11,borderRadius:9}}>No opportunity-level execution reservation is recorded yet for this campaign.</div>}</div>
  <details><summary style={{cursor:"pointer",fontWeight:800}}>Show execution detail</summary><div style={{display:"grid",gap:10,marginTop:12}}>{phaseOrder.map(type=>{const actions=c.actions.filter(a=>a.actionType===type),targets=[...new Set(actions.map(a=>a.executionTarget).filter(Boolean))] as string[];return <div key={type} style={{border:"1px solid #e5e7eb",borderRadius:10,padding:"10px 12px"}}><strong>{actionLabel[type]}</strong>{targets.length?<div style={{fontSize:12,color:"#6b7280",marginTop:5}}>{targets.length} target{targets.length===1?"":"s"}</div>:<div style={{fontSize:13,color:"#6b7280",marginTop:5}}>No separate action recorded.</div>}</div>})}</div></details></article>})}</section>
 </main>
}
function Stat({label,value,small=false}:{label:string;value:string|number;small?:boolean}){return <div style={{border:"1px solid #e5e7eb",borderRadius:12,padding:16,background:"#fafafa"}}><div style={{fontSize:12,color:"#6b7280",fontWeight:800,textTransform:"uppercase"}}>{label}</div><div style={{fontSize:small?16:28,fontWeight:800,marginTop:6}}>{value}</div></div>}
const noticeStyle={border:"1px solid #dbeafe",background:"#eff6ff",color:"#1e3a8a",padding:14,borderRadius:10,marginBottom:18};
const linkStyle={padding:"10px 14px",border:"1px solid #d1d5db",borderRadius:9,textDecoration:"none",color:"#111827",fontWeight:700};
const darkButton={padding:"10px 14px",border:"1px solid #111827",borderRadius:9,background:"#111827",color:"white",fontWeight:700,cursor:"pointer"} as const;
