"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Action={id:string;actionType:string;description:string;executionTarget?:string|null;completed?:boolean;resultSummary?:string|null};
type Recommendation={id:string;title:string;status:string;actions:Action[]};
type Campaign={id:string;name:string;objective?:string|null;startDate:string;endDate:string;status:string;createdAt?:string;products:{product:{sku:string;name:string}}[];recommendations:Recommendation[]};
type CampaignInstance=Campaign&{sourceIds:string[];actions:Action[];recommendations:Recommendation[]};
type Opportunity={id:string;label:string;channel:string;state:string;next:string};

function instanceKey(c:Campaign){const skus=c.products.map(p=>p.product.sku).sort().join(",");return[c.name.trim().toLowerCase(),c.startDate.slice(0,10),skus].join("|")}
function actionKey(a:Action){return[a.actionType,a.executionTarget??"",a.description].join("|")}
function parseTarget(a:Action){try{return a.executionTarget?JSON.parse(a.executionTarget):null}catch{return null}}
function result(a?:Action){if(!a)return{};try{return a.resultSummary?JSON.parse(a.resultSummary):{}}catch{return{}}}
function dayStart(value:Date|string){const d=new Date(value);return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()}
function campaignState(c:CampaignInstance){if(c.status==="PAUSED")return"STOPPED";if(c.status==="COMPLETED")return"COMPLETED";const now=dayStart(new Date()),start=dayStart(c.startDate),end=dayStart(c.endDate);if(now<start)return"SCHEDULED";if(now<=end)return"ACTIVE";return"COMPLETED"}
function campaignDay(c:CampaignInstance){const now=dayStart(new Date()),start=dayStart(c.startDate),end=dayStart(c.endDate);const total=Math.max(1,Math.floor((end-start)/86400000)+1);if(now<start)return`Starts in ${Math.ceil((start-now)/86400000)} day${Math.ceil((start-now)/86400000)===1?"":"s"}`;if(now>end)return`Campaign window ended · ${total} days`;const current=Math.min(total,Math.floor((now-start)/86400000)+1);return`Day ${current} of ${total}`}
function actionOpportunity(a:Action){const t=parseTarget(a),raw=String(a.executionTarget??"");if(a.actionType==="WORDPRESS_HOMEPAGE_HERO"||t?.opportunityId==="homepage-hero"||raw.includes("homepage-hero"))return"homepage-hero";if(a.actionType==="WORDPRESS_CAMPAIGN_LANDING_PAGE"||t?.opportunityId==="landing-page"||raw.includes("landing-page"))return"landing-page";if(a.actionType==="WORDPRESS_CAMPAIGN_COLLECTION_PAGE"||t?.opportunityId==="collection-page"||raw.includes("collection-page"))return"collection-page";return null}
const opportunityMeta:Record<string,{label:string;channel:string}>={"homepage-hero":{label:"Homepage Hero",channel:"WooCommerce / Website"},"landing-page":{label:"Dedicated Campaign Landing Page",channel:"WooCommerce / Website"},"collection-page":{label:"Campaign Collection Page",channel:"WooCommerce / Website"}};
function recommendationOpportunity(r:Recommendation){const title=r.title.toLowerCase();if(title.includes("homepage hero"))return"homepage-hero";if(title.includes("landing page"))return"landing-page";if(title.includes("collection page"))return"collection-page";return r.actions.map(actionOpportunity).find(Boolean)??null}
function opportunityState(id:string,actions:Action[],campaignStatus:string){const related=actions.filter(a=>actionOpportunity(a)===id);const explicit=related.find(a=>["WORDPRESS_HOMEPAGE_HERO","WORDPRESS_CAMPAIGN_LANDING_PAGE","WORDPRESS_CAMPAIGN_COLLECTION_PAGE"].includes(a.actionType));const r=result(explicit);if(r.error)return"NEEDS ATTENTION";if(r.publishedAt&&!r.restoredAt&&!r.unpublishedAt)return"LIVE";if(explicit?.completed&&(r.restoredAt||r.unpublishedAt))return"COMPLETED";const approved=related.some(a=>a.actionType==="CREATIVE_APPROVED");const scheduled=related.some(a=>a.actionType==="SCHEDULE_EXECUTION"&&a.completed);if(campaignStatus==="ACTIVE"&&scheduled)return"READY TO EXECUTE";if(scheduled)return"SCHEDULED";if(approved)return"READY TO SCHEDULE";return"READY TO BUILD"}
function nextStep(state:string){if(state==="LIVE")return"Running now";if(state==="READY TO EXECUTE")return"Execute approved asset";if(state==="SCHEDULED")return"Waiting for scheduled start";if(state==="READY TO SCHEDULE")return"Choose execution time";if(state==="COMPLETED")return"No action needed";if(state==="NEEDS ATTENTION")return"Review problem";return"Create / approve asset"}
function deriveOpportunities(c:CampaignInstance){const ids=new Set<string>();for(const r of c.recommendations){const id=recommendationOpportunity(r);if(id)ids.add(id)}for(const a of c.actions){const id=actionOpportunity(a);if(id)ids.add(id)}const status=campaignState(c);return[...ids].map(id=>{const meta=opportunityMeta[id];const state=opportunityState(id,c.actions,status);return{id,label:meta?.label??id,channel:meta?.channel??"Campaign",state,next:nextStep(state)}})}

export default function CampaignExecutionPage(){
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[stopping,setStopping]=useState<string|null>(null),[notice,setNotice]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/campaigns",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load campaigns");setCampaigns(d.campaigns??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load campaigns")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function stopCampaign(c:CampaignInstance){if(!window.confirm(`EMERGENCY STOP ${c.name}?\n\nThis will cancel remaining scheduled work and immediately withdraw any live campaign website opportunities.`))return;setStopping(c.id);setNotice("");try{const r=await fetch(`/api/campaigns/${c.id}/stop`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to stop campaign");setNotice(`${c.name} stopped. ${d.outcomes?.join(" ")||"Remaining execution cancelled."}`);await load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to stop campaign")}finally{setStopping(null)}}
 const instances=useMemo(()=>{const grouped=new Map<string,CampaignInstance>();for(const c of campaigns){const key=instanceKey(c),currentActions=c.recommendations.flatMap(r=>r.actions??[]),existing=grouped.get(key);if(!existing){grouped.set(key,{...c,sourceIds:[c.id],actions:currentActions,recommendations:c.recommendations});continue}const base=(c.createdAt??"")>=(existing.createdAt??"")?c:existing,mergedActions=[...existing.actions,...currentActions].filter((a,i,all)=>all.findIndex(x=>actionKey(x)===actionKey(a))===i),mergedRecommendations=[...existing.recommendations,...c.recommendations].filter((r,i,all)=>all.findIndex(x=>x.id===r.id)===i);grouped.set(key,{...base,sourceIds:[...existing.sourceIds,c.id],actions:mergedActions,recommendations:mergedRecommendations})}return[...grouped.values()].sort((a,b)=>(b.createdAt??"").localeCompare(a.createdAt??""))},[campaigns]);
 const summary=useMemo(()=>({total:instances.length,active:instances.filter(c=>campaignState(c)==="ACTIVE").length,scheduled:instances.filter(c=>campaignState(c)==="SCHEDULED").length,problems:instances.reduce((n,c)=>n+deriveOpportunities(c).filter(o=>o.state==="NEEDS ATTENTION").length,0)}),[instances]);
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"34px 22px 60px",fontFamily:"Arial, sans-serif"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",flexWrap:"wrap"}}><div><p style={{margin:0,fontSize:12,fontWeight:800,letterSpacing:".12em",textTransform:"uppercase",color:"#6b7280"}}>LMG Marketing · Campaign Operations</p><h1 style={{fontSize:34,margin:"8px 0"}}>Campaign Execution</h1><p style={{maxWidth:800,margin:0,color:"#4b5563",lineHeight:1.55}}>See what is running, what happens next, and whether anything needs attention.</p></div><div style={{display:"flex",gap:10}}><Link href="/campaigns" style={linkStyle}>Back to Builder</Link><button onClick={()=>void load()} style={darkButton}>Refresh status</button></div></div>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,margin:"26px 0"}}><Stat label="Campaigns" value={summary.total}/><Stat label="Active now" value={summary.active}/><Stat label="Scheduled next" value={summary.scheduled}/><Stat label="Problems" value={summary.problems}/></section>
  {notice&&<div style={noticeStyle}>{notice}</div>}{loading&&<div style={noticeStyle}>Loading execution state…</div>}{error&&<div style={{...noticeStyle,borderColor:"#fecaca",background:"#fef2f2",color:"#991b1b"}}>{error}</div>}
  <section style={{display:"grid",gap:18}}>{instances.map(c=>{const status=campaignState(c),opportunities=deriveOpportunities(c),live=opportunities.filter(o=>o.state==="LIVE").length,scheduled=opportunities.filter(o=>["SCHEDULED","READY TO EXECUTE"].includes(o.state)).length,awaiting=opportunities.filter(o=>["READY TO BUILD","READY TO SCHEDULE"].includes(o.state)).length,problems=opportunities.filter(o=>o.state==="NEEDS ATTENTION").length;return <article key={instanceKey(c)} style={{border:"1px solid #e5e7eb",borderRadius:14,padding:20,background:"white"}}>
   <div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"flex-start",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 6px",fontSize:22}}>{c.name}</h2><div style={{fontSize:13,color:"#6b7280"}}>{new Date(c.startDate).toLocaleDateString()} – {new Date(c.endDate).toLocaleDateString()} · {c.products.length} product{c.products.length===1?"":"s"} · <strong>{campaignDay(c)}</strong></div></div><div style={{display:"flex",gap:10,alignItems:"center"}}><span style={{padding:"6px 10px",borderRadius:999,fontSize:12,fontWeight:900,background:status==="STOPPED"?"#fee2e2":status==="ACTIVE"?"#dcfce7":"#eef2ff",color:status==="STOPPED"?"#991b1b":status==="ACTIVE"?"#166534":"#3730a3"}}>{status}</span>{!["STOPPED","COMPLETED"].includes(status)&&<button onClick={()=>void stopCampaign(c)} disabled={stopping===c.id} style={{padding:"11px 16px",border:"2px solid #991b1b",borderRadius:9,background:"#dc2626",color:"white",fontWeight:900,cursor:"pointer"}}>{stopping===c.id?"STOPPING…":"STOP CAMPAIGN"}</button>}</div></div>
   {c.objective&&<p style={{color:"#374151",lineHeight:1.5}}>{c.objective}</p>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{c.products.map(p=><span key={p.product.sku} style={{fontSize:12,padding:"5px 8px",background:"#f3f4f6",borderRadius:7}}>{p.product.name} · {p.product.sku}</span>)}</div>
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8,marginBottom:18}}><MiniStat label="Opportunities" value={opportunities.length}/><MiniStat label="Live" value={live}/><MiniStat label="Scheduled" value={scheduled}/><MiniStat label="Awaiting action" value={awaiting}/><MiniStat label="Problems" value={problems}/></div>
   <div style={{marginBottom:16}}><div style={{fontSize:12,fontWeight:900,letterSpacing:".08em",textTransform:"uppercase",color:"#6b7280",marginBottom:8}}>What is happening</div>{opportunities.length?<div style={{display:"grid",gap:8}}>{opportunities.map(o=><div key={o.id} style={{display:"grid",gridTemplateColumns:"minmax(220px,1.4fr) minmax(120px,.6fr) minmax(180px,1fr)",alignItems:"center",gap:12,border:"1px solid #dbeafe",background:"#f8fbff",borderRadius:10,padding:"11px 13px"}}><div><strong>{o.label}</strong><div style={{fontSize:12,color:"#6b7280",marginTop:3}}>{o.channel}</div></div><strong style={{fontSize:12,color:o.state==="NEEDS ATTENTION"?"#991b1b":o.state==="LIVE"?"#166534":"#374151"}}>{o.state}</strong><div style={{fontSize:13,color:"#4b5563"}}>{o.next}</div></div>)}</div>:<div style={{fontSize:13,color:"#4b5563",background:"#f9fafb",border:"1px solid #e5e7eb",padding:12,borderRadius:9}}>This campaign predates opportunity-level tracking. Its campaign schedule is still valid; new or regenerated campaign assets will appear here by name as they are created.</div>}</div>
   <details><summary style={{cursor:"pointer",fontWeight:800}}>Technical execution detail</summary><div style={{fontSize:13,color:"#6b7280",marginTop:10,lineHeight:1.55}}>For troubleshooting only: {c.actions.length} execution records are attached to this campaign instance. Use the named opportunity table above for day-to-day campaign management.</div></details>
  </article>})}</section>
 </main>
}
function Stat({label,value}:{label:string;value:string|number}){return <div style={{border:"1px solid #e5e7eb",borderRadius:12,padding:16,background:"#fafafa"}}><div style={{fontSize:12,color:"#6b7280",fontWeight:800,textTransform:"uppercase"}}>{label}</div><div style={{fontSize:28,fontWeight:800,marginTop:6}}>{value}</div></div>}
function MiniStat({label,value}:{label:string;value:number}){return <div style={{border:"1px solid #e5e7eb",borderRadius:9,padding:"10px 12px",background:"#fafafa"}}><div style={{fontSize:11,color:"#6b7280",fontWeight:800,textTransform:"uppercase"}}>{label}</div><div style={{fontSize:20,fontWeight:900,marginTop:4}}>{value}</div></div>}
const noticeStyle={border:"1px solid #dbeafe",background:"#eff6ff",color:"#1e3a8a",padding:14,borderRadius:10,marginBottom:18};
const linkStyle={padding:"10px 14px",border:"1px solid #d1d5db",borderRadius:9,textDecoration:"none",color:"#111827",fontWeight:700};
const darkButton={padding:"10px 14px",border:"1px solid #111827",borderRadius:9,background:"#111827",color:"white",fontWeight:700,cursor:"pointer"} as const;
