import {pinterestConfigured,pinterestRequest} from "./client";
import {wooRequest} from "../woocommerce/client";
type Obj=Record<string,any>;
export type BoardHealth="GREEN"|"YELLOW"|"RED";
async function allBoards():Promise<Obj[]>{if(!pinterestConfigured())return[];const out:Obj[]=[];let bookmark:string|undefined;for(let n=0;n<50;n++){const r=await pinterestRequest<any>("/boards",{page_size:100,bookmark});const rows=Array.isArray(r?.items)?r.items:[];out.push(...rows);bookmark=r?.bookmark||undefined;if(!bookmark||!rows.length)break;}return out;}
async function boardPins(boardId:string){const out:Obj[]=[];let bookmark:string|undefined;for(let n=0;n<50;n++){const r=await pinterestRequest<any>(`/boards/${boardId}/pins`,{page_size:100,bookmark}).catch(()=>null);if(!r)break;const rows=Array.isArray(r?.items)?r.items:[];out.push(...rows);bookmark=r?.bookmark||undefined;if(!bookmark||!rows.length)break;}return out;}
async function wooProducts(){const out:Obj[]=[];for(let page=1;page<=100;page++){const rows=await wooRequest<Obj[]>("/products",{status:"publish",per_page:100,page});out.push(...rows);if(rows.length<100)break;}return out;}
const clean=(v:any)=>String(v??"").toLowerCase().replace(/^https?:\/\/(www\.)?/,"").replace(/[?#].*$/,"").replace(/\/$/,"");
const skuFromPin=(p:Obj)=>{const text=`${p?.title??""} ${p?.description??""} ${p?.alt_text??""}`;const m=text.match(/(?:sku[:#\s-]*)?([a-z0-9][a-z0-9_-]{3,})/ig);return m?.map(x=>x.replace(/^sku[:#\s-]*/i,"").toUpperCase())??[];};
export async function getPinterestBoardManager(){const [boards,products]=await Promise.all([allBoards(),wooProducts()]);const enriched:Array<Obj&{pins:Obj[]}>=await Promise.all(boards.map(async(b:Obj)=>({...b,pins:await boardPins(String(b.id))})));
 const productRows=products.map(p=>{const sku=String(p.sku??"");const permalink=clean(p.permalink);const matches:Obj[]=[];for(const b of enriched)for(const pin of b.pins){const link=clean(pin?.link);const skuMatches=sku&&skuFromPin(pin).includes(sku.toUpperCase());if((permalink&&link&&(link===permalink||link.includes(permalink)||permalink.includes(link)))||skuMatches)matches.push({boardId:String(b.id),boardName:String(b.name??"Board"),pinId:String(pin.id??""),pinTitle:String(pin.title??p.name)});}
 const reasons:string[]=[];let health:BoardHealth="GREEN";if(!pinterestConfigured()){health="RED";reasons.push("Pinterest API not connected");}else if(!matches.length){health="RED";reasons.push("No Pinterest board assignment found");}else if(matches.length===1){health="YELLOW";reasons.push("Only one board assignment found; review for additional relevant placement");}
 return{id:p.id,sku,name:p.name,inventory:p.stock_quantity,stockStatus:p.stock_status,price:Number(p.price||0),permalink:p.permalink,image:p.images?.[0]?.src??null,health,reasons,assignments:matches};});
 const boardRows=enriched.map(b=>{const activeMatches=productRows.filter(p=>p.assignments.some((a:any)=>a.boardId===String(b.id))).length;return{id:String(b.id),name:String(b.name??"Board"),description:String(b.description??""),privacy:String(b.privacy??"PUBLIC"),pinCount:b.pins.length,matchedProducts:activeMatches,health:(activeMatches===0?"YELLOW":"GREEN") as BoardHealth,reasons:activeMatches===0?["No active WooCommerce products matched to this board"]:[]};});
 return{configured:pinterestConfigured(),summary:{wooProducts:productRows.length,pinterestBoards:boardRows.length,properlyAssigned:productRows.filter(p=>p.assignments.length>0).length,unassigned:productRows.filter(p=>p.assignments.length===0).length,multipleBoards:productRows.filter(p=>p.assignments.length>1).length,emptyBoards:boardRows.filter(b=>b.matchedProducts===0).length},boards:boardRows,products:productRows};}
export async function createPinterestBoard(name:string,description=""){return pinterestRequest<any>("/boards",{}, {method:"POST",body:JSON.stringify({name,description})});}
export async function updatePinterestBoard(id:string,name:string,description=""){return pinterestRequest<any>(`/boards/${encodeURIComponent(id)}`,{}, {method:"PATCH",body:JSON.stringify({name,description})});}
export async function deletePinterestBoard(id:string){return pinterestRequest<void>(`/boards/${encodeURIComponent(id)}`,{}, {method:"DELETE"});}
export async function createProductPin(boardId:string,product:Obj){const image=product?.images?.[0]?.src;if(!image)throw new Error("WooCommerce product has no image available for Pinterest.");return pinterestRequest<any>("/pins",{}, {method:"POST",body:JSON.stringify({board_id:boardId,title:String(product.name).slice(0,100),description:`${product.short_description||product.description||""}`.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim().slice(0,800),link:product.permalink,alt_text:String(product.name).slice(0,500),media_source:{source_type:"image_url",url:image}})});}
export async function getWooProductById(id:number){return wooRequest<Obj>(`/products/${id}`);}
