import { pinterestConfigured, pinterestRequest } from "./client";
import { wooRequest, woocommerceConfigured } from "../woocommerce/client";

type Health="GREEN"|"YELLOW"|"RED";
type AnyObj=Record<string,any>;
const num=(v:any):number|null=>{if(v==null||v==="")return null;const n=Number(typeof v==="string"?v.replace(/[^0-9.-]/g,""):v);return Number.isFinite(n)?n:null};
const arr=(x:any)=>Array.isArray(x?.items)?x.items:Array.isArray(x)?x:[];
async function safe<T>(fn:()=>Promise<T>){try{return{ok:true as const,data:await fn()}}catch(error){return{ok:false as const,error:error instanceof Error?error.message:"Unavailable"}}}
async function allWooProducts(){if(!woocommerceConfigured())return[];const out:AnyObj[]=[];for(let page=1;page<=100;page++){const rows=await wooRequest<AnyObj[]>("/products",{status:"publish",per_page:100,page}).catch(()=>[]);out.push(...rows);if(rows.length<100)break;}return out;}
export async function getPinterestCatalogHealth(){
 if(!pinterestConfigured())return{connected:false,health:"RED" as Health,summary:{catalogs:0,feeds:0,productGroups:0,wooProducts:0},products:[],issues:[{health:"RED",title:"Pinterest API not connected",detail:"Add Pinterest OAuth/API authorization before catalog diagnostics can inspect live Pinterest items."}]};
 const[catalogsR,feedsR,groupsR,woo]=await Promise.all([safe(()=>pinterestRequest<any>("/catalogs",{page_size:100})),safe(()=>pinterestRequest<any>("/catalogs/feeds",{page_size:100})),safe(()=>pinterestRequest<any>("/catalogs/product_groups",{page_size:100})),allWooProducts()]);
 const catalogs=catalogsR.ok?arr(catalogsR.data):[];const feeds=feedsR.ok?arr(feedsR.data):[];const groups=groupsR.ok?arr(groupsR.data):[];const issues:any[]=[];
 if(!catalogs.length)issues.push({health:"RED",title:"No Pinterest catalog detected",detail:"Shopping distribution requires an accessible catalog."});
 if(!feeds.length)issues.push({health:"RED",title:"No catalog feed detected",detail:"No accessible Pinterest catalog feed was returned."});
 if(!groups.length)issues.push({health:"YELLOW",title:"No product groups detected",detail:"Product groups help organize Shop merchandising and catalog-sales campaigns."});
 const processing:any[]=[];for(const feed of feeds.slice(0,10)){const id=String(feed.id??feed.feed_id??"");if(!id)continue;const r=await safe(()=>pinterestRequest<any>(`/catalogs/feeds/${id}/processing_results`,{page_size:25}));if(r.ok)processing.push(...arr(r.data).map((x:any)=>({...x,feedId:id})));}
 for(const p of processing){const status=String(p.status??p.ingestion_details?.status??p.ingestion_details?.ingestion_status??"").toUpperCase();const errors=p.ingestion_details?.errors??p.validation_details?.errors??{};const errorCount=Object.values(errors).reduce((s:number,v:any)=>s+(num(v)??0),0);if(status.includes("FAIL")||errorCount>0)issues.push({health:"RED",title:`Feed ${p.feedId} has ingestion errors`,detail:`Latest processing result reports ${errorCount} error occurrence${errorCount===1?"":"s"}.`});}
 const products=woo.map((p:any)=>{const stock=p.manage_stock?num(p.stock_quantity):p.stock_status==="instock"?null:0;const reasons:string[]=[];let health:Health="GREEN";if(p.stock_status!=="instock"||stock===0){health="RED";reasons.push("Out of stock");}else if(stock!=null&&stock<=3){health="YELLOW";reasons.push(`Low inventory (${stock})`);}if(!p.images?.length){health="RED";reasons.push("Missing product image");}if(!String(p.description??p.short_description??"").replace(/<[^>]*>/g,"").trim()){if(health!=="RED")health="YELLOW";reasons.push("Missing product description");}if(!p.sku){if(health!=="RED")health="YELLOW";reasons.push("Missing SKU");}return{sku:String(p.sku??""),name:String(p.name??"Untitled product"),health,inventory:stock,price:num(p.price),stockStatus:p.stock_status,permalink:p.permalink,image:p.images?.[0]?.src??null,reasons:reasons.length?reasons:["No local catalog problem detected"],pinterestStatus:feeds.length?"Catalog feed connected":"Feed unavailable"};});
 const red=products.filter(p=>p.health==="RED").length,yellow=products.filter(p=>p.health==="YELLOW").length,green=products.filter(p=>p.health==="GREEN").length;const health:Health=issues.some(x=>x.health==="RED")||red?"RED":issues.length||yellow?"YELLOW":"GREEN";
 return{connected:true,health,summary:{catalogs:catalogs.length,feeds:feeds.length,productGroups:groups.length,feedProcessingResults:processing.length,wooProducts:products.length,red,yellow,green},products,issues,dataGaps:["Pinterest item-level distribution status will populate after catalogs:read authorization and item/report retrieval are validated."],checkedAt:new Date().toISOString()};
}
