import { ChannelType } from "@prisma/client";
import { db } from "@/lib/db";
import { pinterestConfigured,pinterestRequest } from "./client";

export type PinterestHealth="GREEN"|"YELLOW"|"RED";
type Finding={layer:string;severity:"CRITICAL"|"WARNING"|"WATCH";title:string;observation:string;likelyCause:string;recommendation:string;confidence:number};
type Check={key:string;label:string;health:PinterestHealth;value:string;detail:string};
async function safe<T>(fn:()=>Promise<T>){try{return{ok:true as const,data:await fn()}}catch(error){return{ok:false as const,error:error instanceof Error?error.message:"Unavailable"}}}

export async function getPinterestConfigHealth(){
 const channel=await db.channel.upsert({where:{type_name:{type:ChannelType.PINTEREST,name:"Pinterest"}},create:{type:ChannelType.PINTEREST,name:"Pinterest",externalSource:"pinterest",externalId:"pinterest"},update:{active:true}});
 const checks:Check[]=[];const findings:Finding[]=[];const gaps:string[]=[];
 const issue=(layer:string,severity:Finding["severity"],title:string,observation:string,likelyCause:string,recommendation:string,confidence=.95)=>findings.push({layer,severity,title,observation,likelyCause,recommendation,confidence});
 const push=(key:string,label:string,health:PinterestHealth,value:string,detail:string)=>checks.push({key,label,health,value,detail});
 if(!pinterestConfigured()){
  push("api-token","Pinterest API authorization","RED","Not configured","LMG Marketing does not currently have a Pinterest access token.");
  issue("API_AUTH","CRITICAL","Pinterest API is not connected","No PINTEREST_ACCESS_TOKEN is configured.","LMG Marketing cannot inspect or safely correct Pinterest settings without OAuth authorization.","Connect Pinterest OAuth/API access with the required read scopes first.",1);
  return{channelId:channel.id,channelName:channel.name,health:"RED" as PinterestHealth,checks,findings,dataGaps:["business account","claimed website","ad accounts","catalog feeds","boards"],checkedAt:new Date().toISOString()};
 }
 const[user,websites,ads,feeds,boards]=await Promise.all([
  safe(()=>pinterestRequest<any>("/user_account")),
  safe(()=>pinterestRequest<any>("/user_account/websites")),
  safe(()=>pinterestRequest<any>("/ad_accounts",{page_size:100})),
  safe(()=>pinterestRequest<any>("/catalogs/feeds",{page_size:100})),
  safe(()=>pinterestRequest<any>("/boards",{page_size:100})),
 ]);
 if(user.ok){const u=user.data??{};const username=String(u.username??u.business_name??u.name??"Connected account");const accountType=String(u.account_type??u.accountType??"").toUpperCase();const business=accountType.includes("BUSINESS")||Boolean(u.business_name);push("account","Pinterest account","GREEN",username,"Pinterest API authorization is valid.");push("business-account","Business account",business?"GREEN":"YELLOW",business?"Confirmed":"Not confirmed",business?"Business-account evidence is present.":"Pinterest did not clearly identify this token user as a business account.");if(!business)issue("ACCOUNT_SETTINGS","WARNING","Business-account status is not confirmed","Pinterest authenticated successfully, but business-account status was not evident in the response.","Shopping, ads and advanced analytics depend on business access.","Confirm the Pinterest profile is a Business account and that the authorized user has appropriate business access.",.85);}else{push("account","Pinterest account","RED","Authorization failed",user.error);issue("API_AUTH","CRITICAL","Pinterest API authorization failed",user.error,"The token may be expired, revoked, invalid, or missing required scopes.","Reconnect Pinterest and generate a current OAuth token with the required scopes.",.99);}
 if(websites.ok){const rows=Array.isArray(websites.data?.items)?websites.data.items:Array.isArray(websites.data)?websites.data:[];const claimed=rows.filter((x:any)=>String(x.status??"").toUpperCase().includes("SUCCESS")||String(x.status??"").toUpperCase().includes("VERIFIED")||x.verified_at);const lmg=claimed.find((x:any)=>String(x.website??"").toLowerCase().includes("laughingmoosegifts.com"));push("claimed-domain","Claimed website",lmg?"GREEN":"RED",lmg?String(lmg.website):`${claimed.length} claimed`,lmg?"laughingmoosegifts.com is claimed by Pinterest.":"The LMG domain was not confirmed among claimed websites.");if(!lmg)issue("DOMAIN_CLAIM","CRITICAL","LMG website claim is not confirmed","Pinterest did not return laughingmoosegifts.com as a verified/claimed website.","A claimed website is required for full shopping/catalog capabilities and improves attribution/organic analytics.","Verify and claim laughingmoosegifts.com in Pinterest before relying on catalog or conversion diagnostics.",.98);}else gaps.push("claimed website");
 if(ads.ok){const rows=Array.isArray(ads.data?.items)?ads.data.items:Array.isArray(ads.data)?ads.data:[];push("ad-accounts","Ad accounts",rows.length?"GREEN":"YELLOW",`${rows.length} available`,rows.length?"Pinterest returned accessible ad accounts.":"No accessible Pinterest ad account was returned.");if(!rows.length)issue("ADS_CONFIGURATION","WARNING","No Pinterest ad account is available","Pinterest returned zero accessible ad accounts.","The account may not have Ads configured, billing/agreements complete, or the token lacks ads access.","Confirm the LMG Pinterest ad account, business access, advertising agreement and billing configuration.",.9);}else gaps.push("ad accounts");
 if(feeds.ok){const rows=Array.isArray(feeds.data?.items)?feeds.data.items:Array.isArray(feeds.data)?feeds.data:[];push("catalog-feeds","Catalog feeds",rows.length?"GREEN":"RED",`${rows.length} feed${rows.length===1?"":"s"}`,rows.length?"Pinterest catalog feed access is working.":"No Pinterest catalog feed was returned.");if(!rows.length)issue("CATALOG_CONFIGURATION","CRITICAL","No Pinterest catalog feed detected","Pinterest returned no catalog feeds for the authorized account.","Shopping product Pins and catalog-sales advertising depend on an active catalog/feed connection.","Connect or restore the WooCommerce/Pinterest catalog feed and confirm ingestion succeeds.",.98);}else{gaps.push("catalog feeds");issue("DATA_GAP","WATCH","Catalog configuration could not be inspected",feeds.error,"The token may not include catalogs:read or the authorized user may lack catalog permissions.","Grant catalogs:read and appropriate Catalogs Manager/Business Access permissions.",1);}
 if(boards.ok){const rows=Array.isArray(boards.data?.items)?boards.data.items:Array.isArray(boards.data)?boards.data:[];push("boards","Boards",rows.length?"GREEN":"YELLOW",`${rows.length} visible`,rows.length?"Pinterest boards are readable for organization diagnostics.":"No boards were returned.");if(!rows.length)issue("CONTENT_ORGANIZATION","WATCH","No Pinterest boards were returned","The API did not return any boards for the authorized account.","Boards are the organizational structure for organic Pins and merchandising themes.","Confirm boards exist and the token includes boards:read.",.8);}else gaps.push("boards");
 for(const gap of gaps)issue("DATA_GAP","WATCH",`${gap} could not be inspected`,`Pinterest did not return ${gap}.`,`Permissions/scopes or account access may be incomplete.`,`Verify the Pinterest OAuth scopes and business permissions needed to read ${gap}.`,1);
 const health:PinterestHealth=findings.some(f=>f.severity==="CRITICAL")?"RED":findings.length?"YELLOW":"GREEN";
 return{channelId:channel.id,channelName:channel.name,health,checks,findings,dataGaps:gaps,checkedAt:new Date().toISOString()};
}
