import {wooRequest} from "./client";

type Product={id:number;name:string;sku:string;status:string;stock_status:string;stock_quantity:number|null;price:string;regular_price:string;sale_price:string;catalog_visibility:string;type:string;permalink?:string};
type Order={id:number;status:string;total:string;date_created:string;line_items?:Array<{product_id:number;quantity:number;total:string}>};
export type WooSnapshot={catalog:{total:number;published:number;draft:number;privateCount:number;outOfStock:number;lowStock:number;missingSku:number;hidden:number};sales:{orders7:number;revenue7:number;units7:number;ordersPrior7:number;revenuePrior7:number;unitsPrior7:number};telemetry:{trafficAvailable:boolean;conversionAvailable:boolean;sourceAttributionAvailable:boolean};samples:Array<{id:number;sku:string;name:string;stock:number|null;stockStatus:string;price:number|null;status:string;visibility:string}>};
const n=(v:any)=>{const x=Number(v);return Number.isFinite(x)?x:0};
async function allProducts(){const out:Product[]=[];for(let page=1;page<=100;page++){const rows=await wooRequest<Product[]>("/products",{per_page:100,page});out.push(...rows);if(rows.length<100)break;}return out;}
async function ordersBetween(after:string,before:string){const out:Order[]=[];for(let page=1;page<=20;page++){const rows=await wooRequest<Order[]>("/orders",{per_page:100,page,after,before,status:"any"});out.push(...rows);if(rows.length<100)break;}return out;}
function orderSummary(rows:Order[]){return rows.filter(o=>!["cancelled","failed","refunded","trash"].includes(String(o.status))).reduce((a,o)=>{a.orders++;a.revenue+=n(o.total);for(const li of o.line_items??[])a.units+=n(li.quantity);return a},{orders:0,revenue:0,units:0});}
export async function getWooDiagnosticSnapshot():Promise<WooSnapshot>{const now=new Date();const d7=new Date(now.getTime()-7*86400000);const d14=new Date(now.getTime()-14*86400000);const[products,current,prior]=await Promise.all([allProducts(),ordersBetween(d7.toISOString(),now.toISOString()),ordersBetween(d14.toISOString(),d7.toISOString())]);const published=products.filter(p=>p.status==="publish");const c=orderSummary(current),p=orderSummary(prior);return{catalog:{total:products.length,published:published.length,draft:products.filter(x=>x.status==="draft").length,privateCount:products.filter(x=>x.status==="private").length,outOfStock:published.filter(x=>x.stock_status==="outofstock").length,lowStock:published.filter(x=>x.stock_quantity!=null&&x.stock_quantity>0&&x.stock_quantity<=3).length,missingSku:published.filter(x=>!String(x.sku??"").trim()).length,hidden:published.filter(x=>x.catalog_visibility==="hidden").length},sales:{orders7:c.orders,revenue7:c.revenue,units7:c.units,ordersPrior7:p.orders,revenuePrior7:p.revenue,unitsPrior7:p.units},telemetry:{trafficAvailable:false,conversionAvailable:false,sourceAttributionAvailable:false},samples:published.slice(0,20).map(x=>({id:x.id,sku:x.sku,name:x.name,stock:x.stock_quantity,stockStatus:x.stock_status,price:x.price?Number(x.price):null,status:x.status,visibility:x.catalog_visibility}))};}
