import {NextResponse} from "next/server";
import {ChannelType} from "@prisma/client";
import {db} from "@/lib/db";
import {getWooConfigHealth} from "@/lib/integrations/woocommerce/config-health";
import {getWebsiteProductHealth} from "@/lib/integrations/woocommerce/product-health";
export const dynamic="force-dynamic";
type Severity="CRITICAL"|"WARNING"|"WATCH";
type Action={id:string;scope:string;layer:string;severity:Severity;title:string;observation:string;recommendation:string;confidence:number;impact:"VERY HIGH"|"HIGH"|"MEDIUM"|"LOW";effort:"LOW"|"MEDIUM"|"HIGH";score:number;sku?:string;source?:string};
const sev=(s:Severity)=>s==="CRITICAL"?40:s==="WARNING"?25:10;const impact=(v:Action["impact"])=>v==="VERY HIGH"?35:v==="HIGH"?25:v==="MEDIUM"?15:5;const effort=(v:Action["effort"])=>v==="LOW"?15:v==="MEDIUM"?8:2;const score=(s:Severity,i:Action["impact"],e:Action["effort"],c:number)=>Math.round(sev(s)+impact(i)+effort(e)+Math.max(0,Math.min(10,c*10)));
function add(a:Omit<Action,"score">):Action{return{...a,score:score(a.severity,a.impact,a.effort,a.confidence)}}
export async function GET(){try{const actions:Action[]=[];const[config,products,channel]=await Promise.all([getWooConfigHealth(),getWebsiteProductHealth(),db.channel.findFirst({where:{type:ChannelType.WOOCOMMERCE,name:"Laughing Moose Gifts Website"}})]);
 for(const f of config.findings){const critical=f.severity==="CRITICAL";actions.push(add({id:`config-${f.layer}-${f.title}`,scope:"Website configuration",layer:f.layer,severity:f.severity,title:f.title,observation:f.observation,recommendation:f.recommendation,confidence:f.confidence,impact:critical?"VERY HIGH":f.layer.includes("CHECKOUT")||f.layer.includes("INVENTORY")?"HIGH":"MEDIUM",effort:f.layer==="DATA_GAP"?"MEDIUM":"LOW"}));}
 for(const p of products.products){if(p.health==="GREEN")continue;const out=p.stockStatus==="outofstock"||p.stock===0;const hidden=p.visibility==="hidden";const converting=p.funnel?.purchases>0;const views=Number(p.funnel?.productViews??0);let severity:Severity=p.health==="RED"?"CRITICAL":"WARNING";let title=p.reasons?.[0]??"Product needs attention";let recommendation=out?"Replenish inventory or retire the product so traffic is not sent to an unavailable item.":hidden?"Restore intended catalog visibility or confirm the product should remain hidden.":views>=20&&!converting?"Improve the product offer/page before increasing paid or social traffic.":"Review the product diagnosis and correct the leading issue.";let imp:Action["impact"]=out||hidden?"HIGH":views>=20?"HIGH":"MEDIUM";actions.push(add({id:`product-${p.sku||p.id}`,scope:`Product ${p.sku||p.id}`,layer:out?"INVENTORY":hidden?"CATALOG":"PRODUCT_CONVERSION",severity,title:`${p.name}: ${title}`,observation:(p.reasons??[]).join(" · ")||"Product health is below green.",recommendation,confidence:.9,impact:imp,effort:out?"MEDIUM":"LOW",sku:p.sku||undefined}));}
 if(channel){const since=new Date(Date.now()-7*86400000);const rows=await db.funnelMetric.findMany({where:{channelId:channel.id,date:{gte:since},source:{startsWith:"lmg-analytics:"}}});const g=new Map<string,{sessions:number;views:number;carts:number;checkouts:number;purchases:number;revenue:number}>();for(const r of rows){const source=r.source.replace(/^lmg-analytics:/,"")||"other";const a=g.get(source)??{sessions:0,views:0,carts:0,checkouts:0,purchases:0,revenue:0};a.sessions+=r.sessions;a.views+=r.productViews;a.carts+=r.addToCarts;a.checkouts+=r.checkoutStarts;a.purchases+=r.purchases;a.revenue+=Number(r.revenue);g.set(source,a);}for(const[source,a]of g){if(a.sessions<10)continue;const conv=a.sessions?a.purchases/a.sessions:0;let stage="TRAFFIC";let observation="";let recommendation="";let severity:Severity="WATCH";let imp:Action["impact"]="MEDIUM";if(a.sessions>=20&&a.views/a.sessions<.25){stage="ENGAGEMENT";severity="WARNING";observation=`${a.sessions} sessions generated only ${a.views} product views.`;recommendation="Improve landing-page relevance and link this source more directly to shoppable product pages.";}else if(a.views>=20&&a.carts===0){stage="PRODUCT_CONVERSION";severity="WARNING";observation=`${a.views} product views generated no add-to-carts.`;recommendation="Improve price, imagery, copy, offer clarity and source-to-product message match before buying more traffic.";imp="HIGH";}else if(a.carts>=5&&a.checkouts/a.carts<.3){stage="CART_CHECKOUT";severity="WARNING";observation=`${a.carts} carts generated only ${a.checkouts} checkout starts.`;recommendation="Inspect shipping-cost surprises, cart friction, coupon behavior and checkout calls-to-action.";imp="HIGH";}else if(a.checkouts>=3&&a.purchases===0){stage="CHECKOUT";severity="CRITICAL";observation=`${a.checkouts} checkout starts generated no purchases.`;recommendation="Inspect payment failures, shipping options, checkout errors and checkout trust/friction immediately.";imp="VERY HIGH";}else if(a.sessions>=20&&conv<.01){stage="CONVERSION";severity="WARNING";observation=`${a.sessions} sessions converted at ${(conv*100).toFixed(1)}%.`;recommendation="Trace and improve the weakest funnel stage before increasing spend or posting volume.";imp="HIGH";}else continue;actions.push(add({id:`source-${source}-${stage}`,scope:`Traffic source: ${source}`,layer:stage,severity,title:`${source}: ${stage.replaceAll("_"," ").toLowerCase()} problem`,observation,recommendation,confidence:.88,impact:imp,effort:stage==="CHECKOUT"?"MEDIUM":"LOW",source}));}}
 actions.sort((a,b)=>b.score-a.score||b.confidence-a.confidence);return NextResponse.json({channelId:channel?.id??null,channelName:channel?.name??"Laughing Moose Gifts Website",generatedAt:new Date().toISOString(),actions,summary:{total:actions.length,critical:actions.filter(a=>a.severity==="CRITICAL").length,warning:actions.filter(a=>a.severity==="WARNING").length,watch:actions.filter(a=>a.severity==="WATCH").length}});}catch(error){return NextResponse.json({message:error instanceof Error?error.message:"Unable to build website action queue."},{status:500});}}
