"use client";
import {useEffect,useMemo,useState} from "react";
import LmgTopNav from "@/components/LmgTopNav";
type Campaign={id:string;name:string;status:string};
type Metrics={campaign:Campaign;summary:{revenue:number;units:number;sessions:number;purchases:number;conversionRate:number;revenuePerSession:number};baseline:{revenue:number;units:number;sessions:number;purchases:number;conversionRate:number};channels:{name:string;revenue:number;units:number;sessions:number;purchases:number;conversionRate:number}[];products:{sku:string;name:string;revenue:number;units:number;sessions:number;purchases:number;conversionRate:number}[]};
type Finding={severity:"positive"|"warning"|"critical"|"info";title:string;evidence:string;cause:string;recommendation:string;confidence:number;approval:boolean};
const pct=(n:number)=>`${n.toFixed(1)}%`;
function diagnose(d:Metrics):Finding[]{const out:Finding[]=[];const b=d.baseline,s=d.summary;const rev=b.revenue?(s.revenue-b.revenue)/b.revenue*100:0,traffic=b.sessions?(s.sessions-b.sessions)/b.sessions*100:0,conv=b.conversionRate?s.conversionRate-b.conversionRate:0;
 if(b.revenue>0&&rev<-20)out.push({severity:"critical",title:`Revenue is ${Math.abs(rev).toFixed(0)}% below baseline`,evidence:`Campaign revenue is materially below the equal-length pre-campaign period.`,cause:traffic<-15?"Traffic volume is a primary contributor.":conv<-0.5?"Conversion deterioration is a primary contributor.":"Revenue weakness is spread across traffic/product mix rather than one obvious funnel break.",recommendation:traffic<-15?"Increase qualified exposure on the strongest channels and inspect launch/scheduling failures.":"Review offer, landing-page/product-page fit and the weakest-converting promoted products before adding spend.",confidence:86,approval:false});
 if(b.sessions>0&&traffic>20&&conv<-0.5)out.push({severity:"warning",title:"Traffic is up, but conversion is down",evidence:`Sessions are ${traffic.toFixed(0)}% above baseline while conversion moved from ${pct(b.conversionRate)} to ${pct(s.conversionRate)}.`,cause:"The campaign is attracting visitors without converting them at the historical rate.",recommendation:"Inspect message-to-product alignment, landing pages, price/offer competitiveness and checkout friction before increasing traffic spend.",confidence:91,approval:false});
 const best=[...d.channels].filter(x=>x.sessions>=20).sort((a,b)=>b.conversionRate-a.conversionRate)[0],worst=[...d.channels].filter(x=>x.sessions>=20).sort((a,b)=>a.conversionRate-b.conversionRate)[0];
 if(best&&worst&&best.name!==worst.name&&best.conversionRate>worst.conversionRate*1.5)out.push({severity:"positive",title:`${best.name} is the strongest converting channel`,evidence:`${best.name} converts at ${pct(best.conversionRate)} versus ${pct(worst.conversionRate)} on ${worst.name}.`,cause:"Channel quality or audience/message fit is materially stronger.",recommendation:`Favor ${best.name} in the next optimization cycle and review whether budget/exposure can be shifted from ${worst.name}.`,confidence:82,approval:true});
 const weak=d.products.filter(p=>p.sessions>=15&&p.conversionRate<Math.max(.5,s.conversionRate*.5)).sort((a,b)=>b.sessions-a.sessions)[0];if(weak)out.push({severity:"warning",title:`${weak.name} is receiving traffic without enough sales`,evidence:`${weak.sessions} sessions with ${pct(weak.conversionRate)} conversion.`,cause:"Product/offer fit, merchandising, price, or campaign-message alignment may be weak.",recommendation:`Review ${weak.name}'s product page and offer; consider removing it from paid emphasis until conversion improves.`,confidence:78,approval:true});
 if(!out.length)out.push({severity:"info",title:"No material campaign anomaly detected yet",evidence:"Current campaign results do not cross the first-pass diagnostic thresholds.",cause:"Performance is broadly consistent with the available baseline or there is not yet enough data.",recommendation:"Continue collecting data and rerun diagnostics as traffic and purchases accumulate.",confidence:70,approval:false});return out;}
export default function Diagnostics(){const[campaigns,setCampaigns]=useState<Campaign[]>([]),[id,setId]=useState(""),[data,setData]=useState<Metrics|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{fetch('/api/campaigns',{cache:'no-store'}).then(r=>r.json()).then(x=>{const c=x.campaigns??[];setCampaigns(c);if(c[0])setId(c[0].id)})},[]);useEffect(()=>{if(!id)return;setLoading(true);fetch(`/api/campaigns/${id}/metrics`,{cache:'no-store'}).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[id]);const findings=useMemo(()=>data?diagnose(data):[],[data]);return <main className="diag-shell"><LmgTopNav active="/campaigns/diagnostics"/><header className="diag-hero"><p className="eyebrow">Campaign Intelligence</p><h1>Diagnostic & Optimization Center</h1><p>Turn campaign measurements into causes, confidence-ranked findings and recommended corrective actions.</p></header><section className="diag-picker"><label>Campaign<select value={id} onChange={e=>setId(e.target.value)}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div><strong>{findings.length}</strong><span>current findings</span></div></section>{loading?<section className="diag-panel">Running diagnostics…</section>:<section className="findings">{findings.map((f,i)=><article className={`finding ${f.severity}`} key={i}><div className="finding-top"><span>{f.severity}</span><b>{f.confidence}% confidence</b></div><h2>{f.title}</h2><div className="finding-grid"><div><small>Evidence</small><p>{f.evidence}</p></div><div><small>Likely cause</small><p>{f.cause}</p></div><div><small>Recommended action</small><p>{f.recommendation}</p></div></div><footer>{f.approval?<><button>Approve Recommended Action</button><button className="secondary">Dismiss</button><em>Human approval required before execution.</em></>:<em>Observation only — no campaign change proposed.</em>}</footer></article>)}</section>}<section className="diag-panel"><p className="eyebrow">Diagnostic architecture</p><h2>Expected → Actual → Cause → Recommendation → Approval → Outcome</h2><p>Approved corrective actions will next be written back to the campaign execution layer so their results can be measured and learned from.</p></section></main>}