import {NextResponse} from "next/server";

const site=(process.env.WOOCOMMERCE_URL||"https://laughingmoosegifts.com").replace(/\/$/,"");
const username=process.env.WORDPRESS_USERNAME||"";
const appPassword=(process.env.WORDPRESS_APPLICATION_PASSWORD||"").replace(/\s+/g,"");
function authHeader(){return `Basic ${Buffer.from(`${username}:${appPassword}`).toString("base64")}`;}
async function wp(path:string){const response=await fetch(`${site}/wp-json${path}`,{headers:{Authorization:authHeader(),Accept:"application/json"},cache:"no-store"});const text=await response.text();let body:any;try{body=JSON.parse(text);}catch{body=null;}return {ok:response.ok,status:response.status,body};}
function strip(html:string){return html.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function coverSummaries(raw:string){const out:any[]=[];const re=/<!--\s+wp:cover(?:\s+({[^>]*}))?\s*-->([\s\S]*?)<!--\s+\/wp:cover\s*-->/g;let m;let i=0;while((m=re.exec(raw))){let attrs:any={};try{attrs=m[1]?JSON.parse(m[1]):{};}catch{}const body=m[2]||"";const headings=[...body.matchAll(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/gi)].map(x=>strip(x[1])).filter(Boolean).slice(0,3);const paragraphs=[...body.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)].map(x=>strip(x[1])).filter(Boolean).slice(0,3);const links=[...body.matchAll(/href=["']([^"']+)["']/gi)].map(x=>x[1]).slice(0,4);out.push({index:i++,attrs:{id:attrs.id||null,url:attrs.url||null,dimRatio:attrs.dimRatio||null,minHeight:attrs.minHeight||null,minHeightUnit:attrs.minHeightUnit||null,align:attrs.align||null},headings,paragraphs,links});}return out;}
function blockSummary(raw:string){const names=[...raw.matchAll(/<!--\s+wp:([^\s{]+)[^>]*-->/g)].map(m=>m[1]);const counts:Record<string,number>={};for(const name of names)counts[name]=(counts[name]||0)+1;return {blockCount:names.length,blockTypes:counts,covers:coverSummaries(raw)};}
export async function GET(){if(!username||!appPassword)return NextResponse.json({ok:false,configured:false},{status:500});const me=await wp("/wp/v2/users/me?context=edit");if(!me.ok)return NextResponse.json({ok:false,configured:true,authenticated:false,wordpressStatus:me.status},{status:502});const settings=await wp("/wp/v2/settings");const homepageId=settings.ok?Number(settings.body?.page_on_front||0):0;let homepage:any=null;if(homepageId){const page=await wp(`/wp/v2/pages/${homepageId}?context=edit`);if(page.ok){const raw=page.body.content?.raw||"";homepage={id:page.body.id,slug:page.body.slug,title:page.body.title?.rendered||page.body.title?.raw||"",status:page.body.status,structure:blockSummary(raw)};}else homepage={id:homepageId,readable:false,wordpressStatus:page.status};}return NextResponse.json({ok:true,configured:true,authenticated:true,user:{id:me.body.id,roles:me.body.roles},settings:settings.ok?{show_on_front:settings.body?.show_on_front,page_on_front:settings.body?.page_on_front}:null,homepage,diagnosticVersion:4});}
