"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Product={sku:string;name:string};
type Campaign={id:string;name:string;objective?:string|null;startDate:string;endDate:string;status:string;products:{product:Product}[]};
type Metrics={campaign:Campaign;summary:{revenue:number;units:number;sessions:number;purchases:number;conversionRate:number;revenuePerSession:number};baseline:{revenue:number;units:number;sessions:number;purchases:number;conversionRate:number};channels:{name:string;revenue:number;units:number;sessions:number;purchases:number;conversionRate:number}[];products:{sku:string;name:string;revenue:number;units:number;sessions:number;purchases:number;conversionRate:number}[]};
const money=(n:number)=>n.toLocaleString("en-US",{style:"currency",currency:"USD"});
const pct=(n:number)=>`${n.toFixed(1)}%`;
export default function CampaignMetricsPage(){
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[id,setId]=useState(""),[data,setData]=useState<Metrics|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/campaigns",{cache:"no-store"}).then(r=>r.json()).then(d=>{const list=d.campaigns??[];setCampaigns(list);if(list[0])setId(list[0].id)}).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!id)return;setLoading(true);fetch(`/api/campaigns/${id}/metrics`,{cache:"no-store"}).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[id]);
 const delta=useMemo(()=>data?{revenue:data.summary.revenue-data.baseline.revenue,units:data.summary.units-data.baseline.units,sessions:data.summary.sessions-data.baseline.sessions,conversion:data.summary.conversionRate-data.baseline.conversionRate}:null,[data]);
 return <main className="metrics-shell"><header className="metrics-hero"><div><p className="eyebrow">LMG Marketing · Campaign Intelligence</p><h1>Campaign Metrics Dashboard</h1><p>Live campaign scoreboard with product and channel contribution plus pre-campaign baseline comparison.</p></div><div className="metrics-actions"><Link href="/campaigns/calendar">Campaign Calendar</Link><Link href="/campaigns">Campaign Builder</Link></div></header>
 <section className="metrics-picker"><label>Campaign<select value={id} onChange={e=>setId(e.target.value)}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{data&&<div><strong>{data.campaign.status}</strong><span>{data.campaign.startDate.slice(0,10)} → {data.campaign.endDate.slice(0,10)}</span></div>}</section>
 {loading?<section className="metrics-panel">Loading campaign metrics…</section>:!data?<section className="metrics-panel">No campaign selected.</section>:<>
 <section className="score-grid">{[["Revenue",money(data.summary.revenue),delta?money(delta.revenue):""],["Units",String(data.summary.units),delta?`${delta.units>=0?"+":""}${delta.units}`:""],["Sessions",data.summary.sessions.toLocaleString(),delta?`${delta.sessions>=0?"+":""}${delta.sessions}`:""],["Purchases",data.summary.purchases.toLocaleString(),""],["Conversion",pct(data.summary.conversionRate),delta?`${delta.conversion>=0?"+":""}${delta.conversion.toFixed(1)} pts`:""],["Revenue / Session",money(data.summary.revenuePerSession),""]].map(([label,value,d])=><article className="score-card" key={label}><span>{label}</span><strong>{value}</strong>{d&&<small>{d} vs baseline</small>}</article>)}</section>
 <section className="metrics-panel"><div className="panel-heading"><div><p className="eyebrow">Expected vs actual</p><h2>Pre-campaign baseline comparison</h2></div><span>Baseline uses an equal-length period immediately before campaign start.</span></div><div className="comparison-grid"><div><span>Revenue</span><strong>{money(data.baseline.revenue)} → {money(data.summary.revenue)}</strong></div><div><span>Units</span><strong>{data.baseline.units} → {data.summary.units}</strong></div><div><span>Sessions</span><strong>{data.baseline.sessions} → {data.summary.sessions}</strong></div><div><span>Conversion</span><strong>{pct(data.baseline.conversionRate)} → {pct(data.summary.conversionRate)}</strong></div></div></section>
 <section className="metrics-two"><div className="metrics-panel"><div className="panel-heading"><div><p className="eyebrow">Channel contribution</p><h2>Where results are coming from</h2></div></div><table><thead><tr><th>Channel</th><th>Revenue</th><th>Units</th><th>Sessions</th><th>Conv.</th></tr></thead><tbody>{data.channels.length?data.channels.map(c=><tr key={c.name}><td><strong>{c.name}</strong></td><td>{money(c.revenue)}</td><td>{c.units}</td><td>{c.sessions}</td><td>{pct(c.conversionRate)}</td></tr>):<tr><td colSpan={5}>No channel-attributed metrics yet.</td></tr>}</tbody></table></div>
 <div className="metrics-panel"><div className="panel-heading"><div><p className="eyebrow">Product performance</p><h2>What is actually selling</h2></div></div><table><thead><tr><th>Product</th><th>Revenue</th><th>Units</th><th>Sessions</th><th>Conv.</th></tr></thead><tbody>{data.products.map(p=><tr key={p.sku}><td><strong>{p.name}</strong><small>{p.sku}</small></td><td>{money(p.revenue)}</td><td>{p.units}</td><td>{p.sessions}</td><td>{pct(p.conversionRate)}</td></tr>)}</tbody></table></div></section>
 <section className="metrics-panel diagnostic-preview"><p className="eyebrow">Next intelligence layer</p><h2>Campaign diagnosis & optimization</h2><p>This scoreboard is now the measurement foundation for Expected vs. Actual diagnostics, anomaly detection, channel/product recommendations and mid-campaign corrective action.</p></section></>}
 </main>;
}