"use client";

import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import ProductFixButton from "./ProductFixButton";
import WalmartProductHealthList from "../[channelId]/WalmartProductHealthList";

type Result={sku:string;requestedSku?:string;resolvedSku?:string|null;name:string;health:"GREEN"|"YELLOW"|"RED";summary:any;findings:Array<any>;nextEvidence:string};
type Perf={status:string;summary?:{rows:number;gmv:number;units:number;authorizedOrders:number;visits:number;productPageviews:number;conversionRate:number|null;dailyAverageVisits:number|null;dailyAverageUnits:number|null};error?:string};

export default function ProductDiagnostics(){
 const[sku,setSku]=useState("");const[result,setResult]=useState<Result|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[perf,setPerf]=useState<Perf>({status:"idle"});
 async function loadPerformance(resolvedSku:string){setPerf({status:"requesting"});try{const r=await fetch("/api/integrations/walmart/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"ITEM_PERFORMANCE"})});const b=await r.json();if(!r.ok||!b.requestId)throw new Error(b.message??"Unable to request performance report.");setPerf({status:"processing"});for(let i=0;i<20;i++){await new Promise(x=>setTimeout(x,3000));const g=await fetch(`/api/integrations/walmart/reports?kind=ITEM_PERFORMANCE&requestId=${encodeURIComponent(b.requestId)}&sku=${encodeURIComponent(resolvedSku)}`,{cache:"no-store"});const body=await g.json();if(!g.ok)throw new Error(body.message??"Unable to retrieve performance report.");if(body.ready){setPerf({status:"ready",summary:body.summary});return;}}setPerf({status:"processing",error:"Walmart is still preparing the Item Performance report. Re-run the product diagnosis shortly."});}catch(e){setPerf({status:"error",error:e instanceof Error?e.message:"Unable to load actual conversion data."});}}
 async function run(value:string){setLoading(true);setError("");setResult(null);setPerf({status:"idle"});try{const r=await fetch(`/api/integrations/walmart/product-diagnostics?sku=${encodeURIComponent(value)}`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.message);setResult(b);void loadPerformance(b.sku);}catch(e){setError(e instanceof Error?e.message:"Unable to diagnose product.")}finally{setLoading(false)}}
 async function submit(e:FormEvent){e.preventDefault();await run(sku)}
 useEffect(()=>{const initial=new URLSearchParams(window.location.search).get("sku")??"";if(initial){setSku(initial);void run(initial);}},[]);
 const s=result?.summary;const actual=perf.summary?.conversionRate??null;const targetMin=actual&&actual>0?Math.ceil(4/actual):null;const targetMax=actual&&actual>0?Math.ceil(6/actual):null;
 return <main><header><p className="eyebrow">Walmart Intelligence</p><h1>Product Diagnostic Workbench</h1><p className="subtitle">SKU → catalog → inventory → offer → Buy Box → visibility → conversion → diagnosis → corrective action</p><p><Link href="/diagnostics">← Diagnostic Center</Link></p></header>
 <section className="panel"><div><h2>Diagnose a Walmart SKU</h2><p>Enter the Sellerchamp/LMG or Walmart seller SKU.</p></div><form onSubmit={submit} style={{display:"flex",gap:10,flexWrap:"wrap"}}><input value={sku} onChange={e=>setSku(e.target.value)} placeholder="Enter SKU" required style={{padding:12,minWidth:280,border:"1px solid #aaa",borderRadius:8}}/><button disabled={loading} style={{padding:"12px 16px",borderRadius:8,fontWeight:700}}>{loading?"Diagnosing…":"Diagnose Product"}</button></form>{error&&<p>{error}</p>}</section>
 {!result&&<WalmartProductHealthList/>}
 {result&&<><section className="panel"><div><p className="eyebrow">PRODUCT HEALTH · {result.health}</p><h2>{result.name}</h2><p>SKU {result.sku}{result.resolvedSku?` · resolved from ${result.requestedSku}`:""}</p></div><div className="modules"><article className="module"><h3>Catalog & inventory</h3><p>Status: <strong>{s.publishStatus}</strong><br/>Product Type: <strong>{s.productType??"—"}</strong><br/>Expected type: <strong>{s.expectedProductType??"—"}</strong><br/>Inventory: <strong>{s.inventory??"—"}</strong><br/>Fulfillment: <strong>{s.fulfillment??"—"}</strong></p></article><article className="module"><h3>Offer</h3><p>Buy Box win: <strong>{s.buyBoxWinRate==null?"—":`${s.buyBoxWinRate.toFixed(1)}%`}</strong><br/>Price competitive: <strong>{s.priceCompetitive==null?"—":s.priceCompetitive?"Yes":"No"}</strong><br/>Current price: <strong>{s.currentPrice==null?"—":`$${s.currentPrice.toFixed(2)}`}</strong><br/>Suggested price: <strong>{s.suggestedPrice==null?"—":`$${s.suggestedPrice.toFixed(2)}`}</strong></p></article><article className="module"><h3>Visibility & demand</h3><p>Walmart traffic band: <strong>{s.traffic??"—"}</strong><br/>30-day GMV: <strong>{s.gmv30==null?"—":`$${s.gmv30.toFixed(2)}`}</strong></p></article></div></section>
 <section className="panel"><div><p className="eyebrow">ACTUAL CONVERSION & TRAFFIC TARGET</p><h2>Traffic required for 4–6 units/day</h2></div><div className="modules"><article className="module"><h3>Walmart Item Performance</h3><p>Status: <strong>{perf.status}</strong></p>{perf.summary&&<p>Actual conversion: <strong>{actual==null?"—":`${(actual*100).toFixed(2)}%`}</strong><br/>Avg. visits/day: <strong>{perf.summary.dailyAverageVisits==null?"—":perf.summary.dailyAverageVisits.toFixed(1)}</strong><br/>Avg. units/day: <strong>{perf.summary.dailyAverageUnits==null?"—":perf.summary.dailyAverageUnits.toFixed(2)}</strong><br/>14-day visits: {perf.summary.visits}<br/>14-day units: {perf.summary.units}</p>}{perf.error&&<p><small>{perf.error}</small></p>}</article><article className="module"><h3>Required traffic</h3>{targetMin&&targetMax?<p>At the product's actual <strong>{(actual!*100).toFixed(2)}%</strong> conversion rate, the target is approximately <strong>{targetMin}–{targetMax} product visits/day</strong> to sell 4–6 units/day.</p>:<p>Actual conversion is still being retrieved. Until then, use the modeled range below.</p>}<p>1%: 400–600/day<br/>2%: 200–300/day<br/>3%: 134–200/day<br/>4%: 100–150/day<br/>5%: 80–120/day</p></article></div></section>
 <section className="panel"><div><p className="eyebrow">ROOT-CAUSE ANALYSIS</p><h2>{result.findings.length?`${result.findings.length} issue${result.findings.length===1?"":"s"} detected`:"No immediate live-data issue detected"}</h2></div><div className="modules">{result.findings.map((f,i)=><article className="module" key={`${f.layer}-${i}`}><p className="eyebrow">{f.layer.replaceAll("_"," ")} · {f.severity}</p><h3>{f.title}</h3><p><strong>Observation:</strong> {f.observation}</p><p><strong>Likely cause:</strong> {f.likelyCause}</p><p><strong>Confidence:</strong> {Math.round(f.confidence*100)}%</p><p><strong>Recommended action:</strong> {f.recommendation}</p><ProductFixButton sku={result.sku} layer={f.layer} title={f.title} observation={f.observation} likelyCause={f.likelyCause} recommendation={f.recommendation} confidence={f.confidence}/></article>)}</div><p><strong>Next evidence:</strong> {result.nextEvidence}</p></section></>}
 </main>
}
