"use client";

import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import ProductFixButton from "./ProductFixButton";
import WalmartProductEditor from "./WalmartProductEditor";
import WalmartProductHealthList from "../[channelId]/WalmartProductHealthList";

type Result={sku:string;requestedSku?:string;resolvedSku?:string|null;name:string;health:"GREEN"|"YELLOW"|"RED";summary:any;findings:Array<any>;nextEvidence:string};
type Perf={status:string;summary?:{rows:number;gmv:number;units:number;authorizedOrders:number;visits:number;productPageviews:number;conversionRate:number|null;dailyAverageVisits:number|null;dailyAverageUnits:number|null};error?:string};
const healthColor=(health:Result["health"])=>health==="RED"?"#dc2626":health==="YELLOW"?"#eab308":"#16a34a";
const money=(v:number|null|undefined)=>v==null?"—":`$${v.toFixed(2)}`;

export default function ProductDiagnostics(){
 const[sku,setSku]=useState("");const[result,setResult]=useState<Result|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[perf,setPerf]=useState<Perf>({status:"idle"});
 async function loadPerformance(resolvedSku:string){setPerf({status:"requesting"});try{const r=await fetch("/api/integrations/walmart/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"ITEM_PERFORMANCE"})});const b=await r.json();if(r.status===429||String(b?.message??"").includes("429")||String(b?.message??"").includes("REQUEST_THRESHOLD_VIOLATED")){setPerf({status:"rate_limited",error:"Walmart is temporarily rate-limiting report requests. The rest of this product diagnosis is still valid; try the performance section again in a few minutes."});return;}if(!r.ok||!b.requestId)throw new Error(b.message??"Unable to request performance report.");setPerf({status:"processing"});const waits=[5000,8000,12000,18000,25000,30000];for(const wait of waits){await new Promise(x=>setTimeout(x,wait));const g=await fetch(`/api/integrations/walmart/reports?kind=ITEM_PERFORMANCE&requestId=${encodeURIComponent(b.requestId)}&sku=${encodeURIComponent(resolvedSku)}`,{cache:"no-store"});const body=await g.json();if(g.status===429||String(body?.message??"").includes("429")||String(body?.message??"").includes("REQUEST_THRESHOLD_VIOLATED")){setPerf({status:"rate_limited",error:"Walmart is temporarily rate-limiting report checks. No further polling was attempted. Try again in a few minutes."});return;}if(!g.ok)throw new Error(body.message??"Unable to retrieve performance report.");if(body.ready){setPerf({status:"ready",summary:body.summary});return;}}setPerf({status:"processing",error:"Walmart is still preparing the Item Performance report. Re-run the product diagnosis later rather than continuously polling."});}catch(e){setPerf({status:"error",error:e instanceof Error?e.message:"Unable to load actual conversion data."});}}
 async function run(value:string){setLoading(true);setError("");setResult(null);setPerf({status:"idle"});try{const r=await fetch(`/api/integrations/walmart/product-diagnostics?sku=${encodeURIComponent(value)}`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.message);setResult(b);window.history.replaceState(null,"",`/diagnostics/product?sku=${encodeURIComponent(b.sku)}`);void loadPerformance(b.sku);}catch(e){setError(e instanceof Error?e.message:"Unable to diagnose product.")}finally{setLoading(false)}}
 async function submit(e:FormEvent){e.preventDefault();await run(sku)}
 function backToList(){setResult(null);setPerf({status:"idle"});setError("");setSku("");window.history.replaceState(null,"","/diagnostics/product");window.scrollTo({top:0,behavior:"smooth"});}
 useEffect(()=>{const initial=new URLSearchParams(window.location.search).get("sku")??"";if(initial){setSku(initial);void run(initial);}},[]);
 const s=result?.summary;const actual=perf.summary?.conversionRate??null;const targetMin=actual&&actual>0?Math.ceil(4/actual):null;const targetMax=actual&&actual>0?Math.ceil(6/actual):null;
 return <main><header><p className="eyebrow">Walmart Intelligence</p><h1>Product Diagnostic Workbench</h1><p className="subtitle">SKU → catalog → inventory → offer → Buy Box → visibility → conversion → diagnosis → corrective action</p><p><Link href="/diagnostics">← Diagnostic Center</Link>{result&&<> · <button type="button" onClick={backToList} style={{border:0,background:"transparent",padding:0,textDecoration:"underline",cursor:"pointer",font:"inherit"}}>← Back to Product List</button></>}</p></header>
 <section className="panel"><div><h2>Diagnose a Walmart SKU</h2><p>Enter the Sellerchamp/LMG or Walmart seller SKU.</p></div><form onSubmit={submit} style={{display:"flex",gap:10,flexWrap:"wrap"}}><input value={sku} onChange={e=>setSku(e.target.value)} placeholder="Enter SKU" required style={{padding:12,minWidth:280,border:"1px solid #aaa",borderRadius:8}}/><button disabled={loading} style={{padding:"12px 16px",borderRadius:8,fontWeight:700}}>{loading?"Diagnosing…":"Diagnose Product"}</button></form>{error&&<p>{error}</p>}</section>
 {!result&&<WalmartProductHealthList/>}
 {result&&<><section className="panel"><div style={{width:"100%"}}><button type="button" onClick={backToList} style={{marginBottom:14,padding:"8px 12px",borderRadius:8}}>← Back to Product List</button><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:10}}><span aria-label={`${result.health.toLowerCase()} product health`} title={`${result.health} product health`} style={{width:22,height:22,borderRadius:"50%",background:healthColor(result.health),display:"inline-block",boxShadow:"0 0 0 4px rgba(0,0,0,.05)"}}/><p className="eyebrow" style={{margin:0}}>PRODUCT HEALTH</p></div><h2>{result.name}</h2><p>SKU {result.sku}{result.resolvedSku?` · resolved from ${result.requestedSku}`:""}</p></div><div className="modules"><article className="module"><h3>Catalog & inventory</h3><p>Status: <strong>{s.publishStatus}</strong><br/>Product Type: <strong>{s.productType??"—"}</strong><br/>Expected type: <strong>{s.expectedProductType??"—"}</strong><br/>Inventory: <strong>{s.inventory??"—"}</strong><br/>Fulfillment: <strong>{s.fulfillment??"—"}</strong></p></article><article className="module"><h3>Offer</h3><p>Buy Box win: <strong>{s.buyBoxWinRate==null?"—":`${s.buyBoxWinRate.toFixed(1)}%`}</strong><br/>Price competitive: <strong>{s.priceCompetitive==null?"—":s.priceCompetitive?"Yes":"No"}</strong><br/>Current price: <strong>{money(s.currentPrice)}</strong><br/>Target price: <strong>{money(s.targetPrice)}</strong><br/>Buy Box price: <strong>{money(s.buyBoxBasePrice)}</strong><br/>Competitor price: <strong>{money(s.competitorPrice)}</strong><br/>Walmart suggested: <strong>{money(s.suggestedPrice)}</strong></p></article><article className="module"><h3>Visibility & demand</h3><p>Walmart traffic band: <strong>{s.traffic??"—"}</strong><br/>30-day GMV: <strong>{s.gmv30==null?"—":`$${s.gmv30.toFixed(2)}`}</strong></p></article></div></section>
 <section className="panel" style={{display:"block"}}><div style={{width:"100%"}}><p className="eyebrow">BUY BOX COMPETITION</p><h2>Competing offers: {s.competingOfferCountLabel??"Not returned"}</h2><p>Our price: <strong>{money(s.currentPrice)}</strong> · Buy Box: <strong>{money(s.buyBoxBasePrice)}</strong> · Competitor benchmark: <strong>{money(s.competitorPrice)}</strong></p>{Array.isArray(s.competingOffers)&&s.competingOffers.length>0?<div style={{display:"grid",gap:8,marginTop:14}}>{s.competingOffers.map((o:any,i:number)=><div key={`${o.sellerName}-${i}`} style={{display:"grid",gridTemplateColumns:"minmax(180px,2fr) repeat(4,minmax(90px,1fr))",gap:12,padding:"10px 12px",border:"1px solid #ddd",borderRadius:8,alignItems:"center"}}><strong>{o.sellerName}</strong><span>{money(o.totalPrice??o.basePrice)}</span><span>{o.fulfillment??(o.wfs?"WFS":"—")}</span><span>{o.shippingSpeed??"—"}</span><span>{o.proSeller?"Pro Seller":""}</span></div>)}</div>:<p>Walmart did not return a competing-offer list for this SKU. Pricing/Buy Box benchmark evidence above is still available where supplied.</p>}<p style={{marginTop:12}}><small>Walmart may expose only the leading competitive offers rather than every seller. A 5+ display should be treated as at least five competing offers, not an exhaustive seller count.</small></p></div></section>
 <WalmartProductEditor sku={result.sku} name={result.name} inventory={s.inventory??null} currentPrice={s.currentPrice??null} targetPrice={s.targetPrice??null} buyBoxBasePrice={s.buyBoxBasePrice??null} buyBoxTotalPrice={s.buyBoxTotalPrice??null} competitorPrice={s.competitorPrice??null} suggestedPrice={s.suggestedPrice??null}/>
 <section className="panel"><div><p className="eyebrow">ACTUAL CONVERSION & TRAFFIC TARGET</p><h2>Traffic required for 4–6 units/day</h2></div><div className="modules"><article className="module"><h3>Walmart Item Performance</h3><p>Status: <strong>{perf.status==="rate_limited"?"temporarily rate-limited":perf.status}</strong></p>{perf.summary&&<p>Actual conversion: <strong>{actual==null?"—":`${(actual*100).toFixed(2)}%`}</strong><br/>Avg. visits/day: <strong>{perf.summary.dailyAverageVisits==null?"—":perf.summary.dailyAverageVisits.toFixed(1)}</strong><br/>Avg. units/day: <strong>{perf.summary.dailyAverageUnits==null?"—":perf.summary.dailyAverageUnits.toFixed(2)}</strong><br/>14-day visits: {perf.summary.visits}<br/>14-day units: {perf.summary.units}</p>}{perf.error&&<p><small>{perf.error}</small></p>}</article><article className="module"><h3>Required traffic</h3>{targetMin&&targetMax?<p>At the product's actual <strong>{(actual!*100).toFixed(2)}%</strong> conversion rate, the target is approximately <strong>{targetMin}–{targetMax} product visits/day</strong> to sell 4–6 units/day.</p>:<p>Actual conversion is not available yet. Until then, use the modeled range below.</p>}<p>1%: 400–600/day<br/>2%: 200–300/day<br/>3%: 134–200/day<br/>4%: 100–150/day<br/>5%: 80–120/day</p></article></div></section>
 <section className="panel"><div><p className="eyebrow">ROOT-CAUSE ANALYSIS</p><h2>{result.findings.length?`${result.findings.length} issue${result.findings.length===1?"":"s"} detected`:"No immediate live-data issue detected"}</h2></div><div className="modules">{result.findings.map((f,i)=><article className="module" key={`${f.layer}-${i}`}><p className="eyebrow">{f.layer.replaceAll("_"," ")} · {f.severity}</p><h3>{f.title}</h3><p><strong>Observation:</strong> {f.observation}</p><p><strong>Likely cause:</strong> {f.likelyCause}</p><p><strong>Confidence:</strong> {Math.round(f.confidence*100)}%</p><p><strong>Recommended action:</strong> {f.recommendation}</p><ProductFixButton sku={result.sku} layer={f.layer} title={f.title} observation={f.observation} likelyCause={f.likelyCause} recommendation={f.recommendation} confidence={f.confidence}/></article>)}</div><p><strong>Next evidence:</strong> {result.nextEvidence}</p></section></>}
 </main>
}
