"use client";
import {useState} from "react";

type Props={sku:string;name:string;inventory:number|null;currentPrice:number|null;targetPrice:number|null;buyBoxBasePrice:number|null;buyBoxTotalPrice:number|null;competitorPrice:number|null;suggestedPrice:number|null};

export default function WalmartProductEditor(props:Props){
 const[price,setPrice]=useState(props.currentPrice==null?"":props.currentPrice.toFixed(2));
 const[inventory,setInventory]=useState(props.inventory==null?"":String(props.inventory));
 const[name,setName]=useState(props.name);
 const[message,setMessage]=useState("");
 const[working,setWorking]=useState(false);
 async function send(action:"PRICE"|"INVENTORY"|"NAME",extra:Record<string,unknown>){setWorking(true);setMessage("");try{const r=await fetch("/api/integrations/walmart/product-update",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sku:props.sku,action,...extra})});const b=await r.json();if(!r.ok)throw new Error(b.message??"Walmart update failed.");setMessage(b.message??"Update accepted.");}catch(e){setMessage(e instanceof Error?e.message:"Walmart update failed.");}finally{setWorking(false)}}
 function updatePrice(){const value=Number(price);if(!Number.isFinite(value)||value<=0){setMessage("Enter a valid price greater than zero.");return;}if(window.confirm(`Update Walmart price for ${props.sku} to $${value.toFixed(2)}?`))void send("PRICE",{price:value});}
 function updateInventory(){const value=Number(inventory);if(!Number.isInteger(value)||value<0){setMessage("Inventory must be a whole number of 0 or greater.");return;}if(window.confirm(`Replace Walmart inventory for ${props.sku} with ${value} units?`))void send("INVENTORY",{quantity:value});}
 function updateName(){if(name.trim()===props.name.trim()){setMessage("Enter a different product name first.");return;}void send("NAME",{name:name.trim()});}
 return <section className="panel" style={{display:"block",width:"100%"}}><p className="eyebrow">PRODUCT CONTROLS</p><h2>Manage this Walmart offer</h2><div className="modules"><article className="module"><h3>Price / Buy Box</h3><p>Current price: <strong>{props.currentPrice==null?"—":`$${props.currentPrice.toFixed(2)}`}</strong><br/>Target price: <strong>{props.targetPrice==null?"—":`$${props.targetPrice.toFixed(2)}`}</strong><br/>Walmart suggested: <strong>{props.suggestedPrice==null?"—":`$${props.suggestedPrice.toFixed(2)}`}</strong><br/>Buy Box item price: <strong>{props.buyBoxBasePrice==null?"—":`$${props.buyBoxBasePrice.toFixed(2)}`}</strong><br/>Buy Box total price: <strong>{props.buyBoxTotalPrice==null?"—":`$${props.buyBoxTotalPrice.toFixed(2)}`}</strong><br/>Competitor price: <strong>{props.competitorPrice==null?"—":`$${props.competitorPrice.toFixed(2)}`}</strong></p><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><span>$</span><input type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} style={{padding:9,width:120}}/><button type="button" disabled={working} onClick={updatePrice} style={{padding:"9px 12px"}}>Update Price</button>{props.targetPrice!=null&&<button type="button" disabled={working} onClick={()=>setPrice(props.targetPrice!.toFixed(2))} style={{padding:"9px 12px"}}>Use Target</button>}</div></article><article className="module"><h3>Inventory</h3><p>Current quantity: <strong>{props.inventory==null?"—":props.inventory}</strong></p><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><input type="number" min="0" step="1" value={inventory} onChange={e=>setInventory(e.target.value)} placeholder="Qty" style={{padding:9,width:120}}/><button type="button" disabled={working} onClick={updateInventory} style={{padding:"9px 12px"}}>Update Inventory</button></div><p style={{marginTop:10}}><small>This replaces Walmart's quantity for the default ship node; use carefully if Sellerchamp or another system also synchronizes inventory.</small></p></article><article className="module"><h3>Product name</h3><p>Current name: <strong>{props.name}</strong></p><textarea value={name} onChange={e=>setName(e.target.value)} rows={3} style={{width:"100%",padding:9,resize:"vertical"}}/><button type="button" disabled={working} onClick={updateName} style={{padding:"9px 12px",marginTop:8}}>Update Product Name</button><p style={{marginTop:10}}><small>Walmart handles title/content edits through its item-maintenance feed rather than the simple price/inventory endpoints. If the update cannot be safely submitted, LMG Marketing will tell you instead of making an unsafe catalog change.</small></p></article></div>{message&&<p><strong>{message}</strong></p>}</section>;
}
