"use client";

import {useEffect,useMemo,useState} from "react";
import {usePathname} from "next/navigation";

type Action={actionType?:string;description?:string};
type Recommendation={title?:string;actions?:Action[]};
type BuilderState={templateName?:string;productSkus?:string[];activeAssets?:string[];opportunities?:Record<string,string[]>;headline?:string;cta?:string;coreMessage?:string};
type Campaign={id:string;name:string;objective?:string|null;startDate:string;endDate:string;status:string;theme?:string|null;products?:{product:{sku:string;name:string}}[];recommendations?:Recommendation[]};
type Snapshot={name:string;startDate:string;endDate:string;objective:string;state:BuilderState};

const ACTIVE_KEY="lmg-active-campaign-id";
const STATE_PREFIX="LMG_BUILDER_STATE:";
const closed=new Set(["COMPLETED","CLOSED","CANCELLED","CANCELED","STOPPED"]);
const assetAliases:[RegExp,string][]=[[/website homepage/i,"Website Homepage"],[/woocommerce/i,"WooCommerce Store"],[/pinterest/i,"Pinterest"],[/tiktok/i,"TikTok"],[/facebook|instagram|meta/i,"Facebook / Instagram"],[/bing|microsoft/i,"Bing / Microsoft Ads"],[/walmart connect|walmart ads/i,"Walmart Connect Ads"],[/walmart/i,"Walmart Marketplace"],[/amazon canada|amazon ca/i,"Amazon Canada Marketplace"],[/amazon ads/i,"Amazon Ads"],[/amazon/i,"Amazon US Marketplace"],[/email/i,"Email"]];

function text(el:Element|null|undefined){return el?.textContent?.trim()??""}
function setValue(el:HTMLInputElement|HTMLTextAreaElement,value:string){const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,"value")?.set?.call(el,value);el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}))}
function dateOnly(v:string){return v?.slice(0,10)??""}
function addDays(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function iso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function durationDays(a:string,b:string){if(!a||!b)return 15;const x=new Date(`${a}T12:00:00`),y=new Date(`${b}T12:00:00`);const n=Math.round((y.getTime()-x.getTime())/86400000)+1;return n>0&&Number.isFinite(n)?Math.min(n,60):15}
function stateFor(c:Campaign):BuilderState{if(!c.theme?.startsWith(STATE_PREFIX))return{};try{return JSON.parse(c.theme.slice(STATE_PREFIX.length)) as BuilderState}catch{return{}}}
function activeAssetFromTitle(title:string){for(const[p,label]of assetAliases)if(p.test(title))return label;return""}
function oldCopy(c:Campaign){for(const rec of c.recommendations??[])for(const a of rec.actions??[]){if(a.actionType!=="CREATIVE_DRAFT"||!a.description?.trim().startsWith("{"))continue;try{return JSON.parse(a.description) as {headline?:string;body?:string;cta?:string}}catch{}}return{}}

export default function CampaignWorkspaceManager(){
 const pathname=usePathname();
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[selectedId,setSelectedId]=useState(""),[currentName,setCurrentName]=useState("New Campaign"),[status,setStatus]=useState("Start a new campaign or resume one already in progress."),[saving,setSaving]=useState(false),[recommendation,setRecommendation]=useState<{start:string;end:string;days:number}|null>(null);
 const resumable=useMemo(()=>campaigns.filter(c=>!closed.has(c.status.toUpperCase())),[campaigns]);

 function step1(){return document.querySelector<HTMLElement>(".campaign-details-card")}
 function messaging(){return Array.from(document.querySelectorAll<HTMLElement>(".campaign-stage-panel")).find(p=>text(p.querySelector("h2")).includes("Edit and approve the campaign messaging"))}
 function snapshot():Snapshot{const root=step1(),inputs=root?Array.from(root.querySelectorAll<HTMLInputElement>("input")):[],name=inputs.find(i=>i.type!=="date")?.value.trim()??"",dates=inputs.filter(i=>i.type==="date"),objective=root?.querySelector<HTMLTextAreaElement>("textarea")?.value??"",templateName=text(root?.querySelector(".template-card.selected strong")),productSkus=Array.from(document.querySelectorAll<HTMLTableRowElement>(".campaign-table tbody tr")).filter(r=>r.querySelector<HTMLInputElement>('input[type="checkbox"]')?.checked).map(r=>text(r.querySelector("td:nth-child(2) small"))).filter(Boolean),activeAssets:string[]=[],opportunities:Record<string,string[]>={};document.querySelectorAll<HTMLElement>("#channels .opportunity-channel-card").forEach(card=>{const asset=text(card.querySelector(".asset-select strong")),on=!!card.querySelector<HTMLInputElement>('.asset-select input[type="checkbox"]')?.checked;if(!asset||!on)return;activeAssets.push(asset);opportunities[asset]=Array.from(card.querySelectorAll<HTMLElement>(".opportunity-option")).filter(o=>o.querySelector<HTMLInputElement>('input[type="checkbox"]')?.checked).map(o=>text(o.querySelector("strong")).replace(/Paid$/,"" ).trim()).filter(Boolean)});const m=messaging(),mi=m?Array.from(m.querySelectorAll<HTMLInputElement>("input")):[],ma=m?Array.from(m.querySelectorAll<HTMLTextAreaElement>("textarea")):[];return{name,startDate:dates[0]?.value??"",endDate:dates[1]?.value??"",objective,state:{templateName,productSkus,activeAssets,opportunities,headline:mi[0]?.value??"",cta:mi[1]?.value??"",coreMessage:ma[0]?.value??""}}}
 function announce(id:string,name:string){try{id?localStorage.setItem(ACTIVE_KEY,id):localStorage.removeItem(ACTIVE_KEY)}catch{}window.dispatchEvent(new CustomEvent("lmg-active-campaign-change",{detail:{id,name}}))}
 function calculateRecommendation(){const snap=snapshot(),days=durationDays(snap.startDate,snap.endDate);let start=addDays(new Date(),8);start.setHours(12,0,0,0);const occupied=resumable.filter(c=>c.id!==selectedId).map(c=>({start:new Date(`${dateOnly(c.startDate)}T12:00:00`),end:new Date(`${dateOnly(c.endDate)}T12:00:00`)})).filter(x=>Number.isFinite(x.start.getTime())&&Number.isFinite(x.end.getTime())).sort((a,b)=>a.start.getTime()-b.start.getTime());for(let i=0;i<120;i++){const end=addDays(start,days-1),hit=occupied.find(x=>start<=x.end&&x.start<=end);if(!hit){setRecommendation({start:iso(start),end:iso(end),days});return}start=addDays(hit.end,1)}setRecommendation({start:iso(start),end:iso(addDays(start,days-1)),days})}
 function clearForm(){const root=step1();if(!root)return;const inputs=Array.from(root.querySelectorAll<HTMLInputElement>("input")),dates=inputs.filter(i=>i.type==="date"),name=inputs.find(i=>i.type!=="date"),objective=root.querySelector<HTMLTextAreaElement>("textarea");if(name)setValue(name,"");dates.forEach(d=>setValue(d,""));if(objective)setValue(objective,"");document.querySelectorAll<HTMLInputElement>('.campaign-table tbody input[type="checkbox"]:checked').forEach(b=>b.click());document.querySelectorAll<HTMLInputElement>('#channels .asset-select input[type="checkbox"]:checked').forEach(b=>b.click());const m=messaging();m?.querySelectorAll<HTMLInputElement>("input").forEach(i=>setValue(i,""));m?.querySelectorAll<HTMLTextAreaElement>("textarea").forEach(a=>setValue(a,""));setCurrentName("New Campaign");announce("","");setStatus("Blank campaign ready. Name it, define as much as you want, and Save Draft before leaving.");setTimeout(calculateRecommendation,0)}
 function wait(work:()=>void){let n=0;const run=()=>{if(step1()&&document.querySelectorAll(".campaign-table tbody tr").length&&document.querySelectorAll("#channels .opportunity-channel-card").length){work();return}if(++n<50)setTimeout(run,100);else setStatus("Campaign builder did not finish loading. Refresh and try again.")};run()}
 function load(c:Campaign){clearForm();const root=step1();if(!root)return;const inputs=Array.from(root.querySelectorAll<HTMLInputElement>("input")),dates=inputs.filter(i=>i.type==="date"),name=inputs.find(i=>i.type!=="date"),objective=root.querySelector<HTMLTextAreaElement>("textarea"),s=stateFor(c);if(name)setValue(name,c.name);if(dates[0])setValue(dates[0],dateOnly(c.startDate));if(dates[1])setValue(dates[1],dateOnly(c.endDate));if(objective)setValue(objective,c.objective??"");const skus=new Set(s.productSkus?.length?s.productSkus:(c.products??[]).map(p=>p.product.sku));document.querySelectorAll<HTMLTableRowElement>(".campaign-table tbody tr").forEach(r=>{const box=r.querySelector<HTMLInputElement>('input[type="checkbox"]');if(box&&skus.has(text(r.querySelector("td:nth-child(2) small")))&&!box.checked)box.click()});const assets=new Set(s.activeAssets??[]);if(!assets.size)(c.recommendations??[]).forEach(r=>{const x=activeAssetFromTitle(r.title??"");if(x)assets.add(x)});document.querySelectorAll<HTMLElement>("#channels .opportunity-channel-card").forEach(card=>{const box=card.querySelector<HTMLInputElement>('.asset-select input[type="checkbox"]');if(box&&assets.has(text(card.querySelector(".asset-select strong")))&&!box.checked)box.click()});setTimeout(()=>{document.querySelectorAll<HTMLElement>("#channels .opportunity-channel-card").forEach(card=>{const asset=text(card.querySelector(".asset-select strong")),wanted=s.opportunities?.[asset]??[];card.querySelectorAll<HTMLElement>(".opportunity-option").forEach(o=>{const box=o.querySelector<HTMLInputElement>('input[type="checkbox"]'),label=text(o.querySelector("strong")).replace(/Paid$/,"" ).trim();if(box&&wanted.includes(label)!==box.checked)box.click()})});const copy=oldCopy(c),m=messaging(),mi=m?Array.from(m.querySelectorAll<HTMLInputElement>("input")):[],ma=m?Array.from(m.querySelectorAll<HTMLTextAreaElement>("textarea")):[];if(mi[0])setValue(mi[0],s.headline??copy.headline??"");if(mi[1])setValue(mi[1],s.cta??copy.cta??"");if(ma[0])setValue(ma[0],s.coreMessage??copy.body??"");setCurrentName(c.name);announce(c.id,c.name);setStatus(`Loaded ${c.name} (${c.status}). Continue editing and save whenever you want.`);calculateRecommendation()},140)}

 useEffect(()=>{if(pathname!=="/campaigns")return;fetch("/api/campaigns",{cache:"no-store"}).then(r=>r.json()).then(d=>setCampaigns(d.campaigns??[])).catch(()=>setStatus("Campaign list could not be loaded."));wait(clearForm)},[pathname]);
 useEffect(()=>{if(pathname!=="/campaigns")return;const changed=()=>{const n=step1()?.querySelector<HTMLInputElement>('input:not([type="date"])')?.value.trim();setCurrentName(n||"New Campaign");calculateRecommendation()};document.addEventListener("input",changed,true);document.addEventListener("change",changed,true);return()=>{document.removeEventListener("input",changed,true);document.removeEventListener("change",changed,true)}},[pathname,campaigns,selectedId]);

 function choose(id:string){setSelectedId(id);if(!id){wait(clearForm);return}const c=campaigns.find(x=>x.id===id);if(c)wait(()=>load(c))}
 function useDates(){if(!recommendation)return;const dates=Array.from(step1()?.querySelectorAll<HTMLInputElement>('input[type="date"]')??[]);if(dates[0])setValue(dates[0],recommendation.start);if(dates[1])setValue(dates[1],recommendation.end);setStatus(`Recommended conflict-free window applied. You can edit either date.`)}
 async function save(){const s=snapshot();if(!s.name){setStatus("Give the campaign a name before saving.");return}setSaving(true);setStatus("Saving draft…");try{const r=await fetch("/api/campaigns/draft",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaignId:selectedId||undefined,name:s.name,objective:s.objective,startDate:s.startDate,endDate:s.endDate,state:s.state})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save draft");const c=d.campaign as Campaign;setCampaigns(cur=>[c,...cur.filter(x=>x.id!==c.id)]);setSelectedId(c.id);setCurrentName(c.name);announce(c.id,c.name);setStatus(`${c.name} saved. It will remain in the resume list until the campaign is completed.`)}catch(e){setStatus(e instanceof Error?e.message:"Unable to save draft.")}finally{setSaving(false)}}

 if(pathname!=="/campaigns")return null;
 return <section style={{maxWidth:1180,margin:"18px auto 4px",display:"grid",gap:12}}>
  <div style={{padding:"16px 20px",borderRadius:15,background:"#183b24",color:"white",boxShadow:"0 8px 24px rgba(25,55,35,.16)"}}><div style={{fontSize:12,fontWeight:900,letterSpacing:".12em",textTransform:"uppercase",opacity:.78}}>Campaign currently being created / edited</div><div style={{fontSize:29,fontWeight:900,marginTop:4}}>{currentName}</div></div>
  <div style={{padding:"16px 18px",border:"1px solid #d7dfd1",borderRadius:14,background:"white",boxShadow:"0 6px 18px rgba(30,50,30,.06)"}}><div style={{display:"grid",gridTemplateColumns:"minmax(250px,1fr) minmax(260px,1fr) auto",gap:14,alignItems:"end"}}>
   <label style={{display:"grid",gap:6,fontWeight:800,color:"#233b27"}}>Campaign to work on<select value={selectedId} onChange={e=>choose(e.target.value)} style={{padding:"10px 12px",border:"1px solid #aebca8",borderRadius:8,background:"white",fontSize:15}}><option value="">+ Start a new campaign (blank)</option>{resumable.map(c=><option key={c.id} value={c.id}>{c.name} · {c.status}</option>)}</select></label>
   <div style={{padding:"9px 12px",borderRadius:9,background:"#f5f8f2",color:"#314c35",fontSize:14}}><strong>Recommended open campaign window</strong><div>{recommendation?`${recommendation.start} → ${recommendation.end} · ${recommendation.days} days`:"Calculating…"}</div><button type="button" onClick={useDates} disabled={!recommendation} style={{marginTop:6,padding:"6px 9px",borderRadius:7,border:"1px solid #8ca18b",background:"white",fontWeight:800}}>Use recommended dates</button></div>
   <button type="button" onClick={save} disabled={saving} style={{padding:"11px 16px",border:0,borderRadius:9,background:"#183b24",color:"white",fontWeight:900,minWidth:130}}>{saving?"Saving…":"Save Draft"}</button>
  </div><p style={{margin:"12px 0 0",padding:"9px 11px",borderRadius:8,background:"#f8faf6",color:"#526052",fontSize:14}}>{status}</p></div>
 </section>;
}
