"use client";

import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {usePathname} from "next/navigation";

type BuilderState={templateName?:string;productSkus?:string[];activeAssets?:string[];opportunities?:Record<string,string[]>;headline?:string;cta?:string;coreMessage?:string};
type Campaign={id:string;name:string;objective?:string|null;startDate:string;endDate:string;status:string;theme?:string|null;products?:{product:{sku:string;name:string}}[]};

const ACTIVE_KEY="lmg-active-campaign-id";
const LEARNING_DRAFT_KEY="lmg-campaign-learning-draft-v1";
const RESUME_OPPS_KEY="lmg-campaign-resume-opportunities-v1";
const STATE_PREFIX="LMG_BUILDER_STATE:";
const closed=new Set(["COMPLETED","CLOSED","CANCELLED","CANCELED","STOPPED"]);
const assetToChannel:Record<string,string>={
  "Website Homepage":"WEBSITE_HOMEPAGE","WooCommerce Store":"WOOCOMMERCE","Pinterest":"PINTEREST","TikTok":"TIKTOK","Facebook / Instagram":"META","Bing / Microsoft Ads":"BING","Walmart Marketplace":"WALMART_MARKETPLACE","Walmart Connect Ads":"WALMART_ADS","Amazon US Marketplace":"AMAZON_US","Amazon Ads":"AMAZON_ADS","Amazon Canada Marketplace":"AMAZON_CA","Email":"EMAIL"
};
function dateOnly(v:string){return v?.slice(0,10)??""}
function parseState(c:Campaign):BuilderState{if(!c.theme?.startsWith(STATE_PREFIX))return{};try{return JSON.parse(c.theme.slice(STATE_PREFIX.length)) as BuilderState}catch{return{}}}
function templateId(name?:string){const s=(name??"").toLowerCase();if(s.includes("seasonal"))return"SEASONAL";if(s.includes("sale")||s.includes("promotional"))return"PROMOTIONAL_EVENT";if(s.includes("launch"))return"PRODUCT_LAUNCH";if(s.includes("spotlight")||s.includes("evergreen"))return"EVERGREEN_SPOTLIGHT";return undefined}
function addDays(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function iso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function durationDays(a:string,b:string){if(!a||!b)return 15;const x=new Date(`${a}T12:00:00`),y=new Date(`${b}T12:00:00`),n=Math.round((y.getTime()-x.getTime())/86400000)+1;return n>0&&Number.isFinite(n)?Math.min(n,60):15}

export default function CampaignWorkspaceV3(){
 const pathname=usePathname();
 const[target,setTarget]=useState<HTMLElement|null>(null),[campaigns,setCampaigns]=useState<Campaign[]>([]),[selectedId,setSelectedId]=useState(""),[status,setStatus]=useState("Start a new campaign or resume one already in progress."),[start,setStart]=useState(""),[end,setEnd]=useState(""),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(false);
 const resumable=useMemo(()=>campaigns.filter(c=>!closed.has(c.status.toUpperCase())),[campaigns]);
 const selected=campaigns.find(c=>c.id===selectedId),canDelete=selected?.status.toUpperCase()==="DRAFT";
 useEffect(()=>{if(pathname!=="/campaigns")return;let cancelled=false,tries=0;const place=()=>{const top=document.querySelector<HTMLElement>(".campaign-topbar");if(top?.parentElement){let t=document.getElementById("campaign-workspace-v3");if(!t){t=document.createElement("div");t.id="campaign-workspace-v3";top.insertAdjacentElement("afterend",t)}if(!cancelled)setTarget(t);return}if(++tries<50)setTimeout(place,100)};place();fetch("/api/campaigns",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{const list=(d.campaigns??[]) as Campaign[];setCampaigns(list);try{const a=localStorage.getItem(ACTIVE_KEY)||"";if(a&&list.some(c=>c.id===a)){const c=list.find(x=>x.id===a)!;setSelectedId(a);setStart(dateOnly(c.startDate));setEnd(dateOnly(c.endDate))}}catch{}}).catch(()=>setStatus("Campaign list could not be loaded."));return()=>{cancelled=true}},[pathname]);
 function choose(id:string){setSelectedId(id);try{if(!id){localStorage.removeItem(ACTIVE_KEY);localStorage.removeItem(RESUME_OPPS_KEY);localStorage.setItem(LEARNING_DRAFT_KEY,JSON.stringify({name:" ",objective:" ",productSkus:[""],channels:[""],startDate:" ",endDate:" ",headline:" ",coreMessage:" ",cta:" ",learningSummary:"Blank campaign"}));location.replace("/campaigns");return}const c=campaigns.find(x=>x.id===id);if(!c){setStatus("That campaign could not be found.");return}const s=parseState(c),channels=(s.activeAssets??[]).map(a=>assetToChannel[a]).filter(Boolean);localStorage.setItem(LEARNING_DRAFT_KEY,JSON.stringify({name:c.name,objective:c.objective??"",productSkus:s.productSkus?.length?s.productSkus:(c.products??[]).map(p=>p.product.sku),channels,startDate:dateOnly(c.startDate),endDate:dateOnly(c.endDate),templateId:templateId(s.templateName),headline:s.headline,coreMessage:s.coreMessage,cta:s.cta,learningSummary:`Resumed ${c.name}`}));localStorage.setItem(RESUME_OPPS_KEY,JSON.stringify({campaignId:c.id,opportunities:s.opportunities??{}}));localStorage.setItem(ACTIVE_KEY,c.id);location.replace("/campaigns")}catch{setStatus("Campaign could not be loaded. Please refresh and try again.")}}
 const days=durationDays(start,end);let rs=addDays(new Date(),8);rs.setHours(12,0,0,0);const occupied=resumable.filter(c=>c.id!==selectedId).map(c=>({s:new Date(`${dateOnly(c.startDate)}T12:00:00`),e:new Date(`${dateOnly(c.endDate)}T12:00:00`)})).filter(x=>Number.isFinite(x.s.getTime())&&Number.isFinite(x.e.getTime())).sort((a,b)=>a.s.getTime()-b.s.getTime());for(let i=0;i<120;i++){const re=addDays(rs,days-1),hit=occupied.find(x=>rs<=x.e&&x.s<=re);if(!hit)break;rs=addDays(hit.e,1)}const rec={start:iso(rs),end:iso(addDays(rs,days-1))};
 async function saveDates(){if(!selected){setStatus("Select a saved campaign before updating its dates.");return}setSaving(true);try{const s=parseState(selected),r=await fetch("/api/campaigns/draft",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaignId:selected.id,name:selected.name,objective:selected.objective??"",startDate:start,endDate:end,state:s})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save dates");setCampaigns(cur=>[d.campaign,...cur.filter(c=>c.id!==selected.id)]);setStatus("Campaign dates saved.")}catch(e){setStatus(e instanceof Error?e.message:"Unable to save dates.")}finally{setSaving(false)}}
 async function deleteDraft(){if(!selected||!canDelete)return;if(!confirm(`Delete draft campaign “${selected.name}”?`))return;setDeleting(true);try{const r=await fetch("/api/campaigns/draft",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaignId:selected.id})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to delete draft");localStorage.removeItem(ACTIVE_KEY);setCampaigns(cur=>cur.filter(c=>c.id!==selected.id));setSelectedId("");setStart("");setEnd("");setStatus(`${selected.name} deleted.`)}catch(e){setStatus(e instanceof Error?e.message:"Unable to delete draft.")}finally{setDeleting(false)}}
 if(pathname!=="/campaigns"||!target)return null;
 const display=selected?.name||"New Campaign";
 return createPortal(<section style={{width:"100%",margin:"14px 0 22px",display:"grid",gap:12}}><div style={{padding:"16px 20px",borderRadius:15,background:"#183b24",color:"white"}}><div style={{fontSize:12,fontWeight:900,letterSpacing:".12em",textTransform:"uppercase",opacity:.78}}>Campaign currently being created / edited</div><div style={{fontSize:29,fontWeight:900,marginTop:4}}>{display}</div></div><div style={{padding:"16px 18px",border:"1px solid #d7dfd1",borderRadius:14,background:"white"}}><div style={{display:"grid",gridTemplateColumns:"minmax(260px,1.3fr) minmax(300px,1fr) auto",gap:14,alignItems:"end"}}><label style={{display:"grid",gap:6,fontWeight:800}}>Campaign to work on<select value={selectedId} onChange={e=>choose(e.target.value)} style={{padding:"10px 12px",border:"1px solid #aebca8",borderRadius:8,background:"white",fontSize:15}}><option value="">+ Start a new campaign (blank)</option>{resumable.map(c=><option key={c.id} value={c.id}>{c.name} · {c.status}</option>)}</select></label><div style={{padding:"9px 12px",borderRadius:9,background:"#f5f8f2"}}><strong>Campaign dates</strong><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:7}}><label>Start<input type="date" value={start} onChange={e=>setStart(e.target.value)} style={{width:"100%",padding:"7px"}}/></label><label>End<input type="date" value={end} onChange={e=>setEnd(e.target.value)} style={{width:"100%",padding:"7px"}}/></label></div><div style={{marginTop:7,fontSize:12}}>Recommended: {rec.start} → {rec.end}</div><button type="button" onClick={()=>{setStart(rec.start);setEnd(rec.end)}} style={{marginTop:5}}>Use recommended dates</button></div><div style={{display:"flex",gap:8}}>{selected&&<button type="button" onClick={saveDates} disabled={saving||deleting}>{saving?"Saving…":"Save Dates"}</button>}{canDelete&&<button type="button" onClick={deleteDraft} disabled={saving||deleting}>{deleting?"Deleting…":"Delete Draft"}</button>}</div></div><p style={{margin:"12px 0 0",padding:"9px 11px",background:"#f8faf6",fontSize:14}}>{status}</p></div></section>,target)
}
