"use client";
import {useEffect,useState} from "react";
import {usePathname} from "next/navigation";

type Preview={opportunityId:string;label:string;campaignName:string;headline:string;body:string;cta:string;imageUrl:string;productSkus:string[];products:{sku:string;name:string;permalink?:string;image?:string|null}[];intendedUrl:string};
const ACTIVE_KEY="lmg-active-campaign-id";
function text(el:Element|null|undefined){return el?.textContent?.trim()??""}
function currentCampaign(){
 const step1=document.querySelector<HTMLElement>(".campaign-details-card"),inputs=step1?Array.from(step1.querySelectorAll<HTMLInputElement>("input")):[],dates=inputs.filter(i=>i.type==="date"),name=inputs.find(i=>i.type!=="date")?.value.trim()??"";
 const skus=Array.from(document.querySelectorAll<HTMLTableRowElement>(".campaign-table tbody tr")).filter(r=>r.querySelector<HTMLInputElement>('input[type="checkbox"]')?.checked).map(r=>text(r.querySelector("td:nth-child(2) small"))).filter(Boolean);
 const messaging=Array.from(document.querySelectorAll<HTMLElement>(".campaign-stage-panel")).find(p=>text(p.querySelector("h2")).includes("Edit and approve the campaign messaging"));
 const mi=messaging?Array.from(messaging.querySelectorAll<HTMLInputElement>("input")):[],ta=messaging?Array.from(messaging.querySelectorAll<HTMLTextAreaElement>("textarea")):[];
 const selectedOps=Array.from(document.querySelectorAll<HTMLElement>("#channels .opportunity-channel-card")).find(c=>text(c.querySelector(".asset-select strong"))==="WooCommerce Store")?.querySelectorAll<HTMLElement>(".opportunity-option")??[];
 const opportunityIds=Array.from(selectedOps).filter(o=>o.querySelector<HTMLInputElement>('input[type="checkbox"]')?.checked).map(o=>text(o.querySelector("strong"))).map(label=>label.includes("Landing Page")?"landing-page":label.includes("Collection Page")?"collection-page":"").filter(Boolean);
 let campaignId="";try{campaignId=localStorage.getItem(ACTIVE_KEY)||""}catch{}
 return{campaignId,name,productSkus:skus,headline:mi[0]?.value??name,cta:mi[1]?.value??"Shop the Campaign",body:ta[0]?.value??"",startAt:dates[0]?.value??"",endAt:dates[1]?.value??"",opportunityIds};
}

export default function WooCommerceCampaignOpportunityBridge(){
 const pathname=usePathname();const[host,setHost]=useState<HTMLElement|null>(null),[preview,setPreview]=useState<Record<string,Preview>>({}),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{if(pathname!=="/campaigns")return;let cancelled=false;const place=()=>{const cards=Array.from(document.querySelectorAll<HTMLElement>("#channels .opportunity-channel-card")),woo=cards.find(c=>text(c.querySelector(".asset-select strong"))==="WooCommerce Store");if(!woo)return false;let h=woo.querySelector<HTMLElement>("[data-lmg-woo-workbench='1']");if(!h){h=document.createElement("div");h.dataset.lmgWooWorkbench="1";h.style.marginTop="14px";woo.appendChild(h)}if(!cancelled)setHost(h);return true};if(!place()){const obs=new MutationObserver(()=>{if(place())obs.disconnect()});obs.observe(document.body,{childList:true,subtree:true});const t=setTimeout(()=>obs.disconnect(),8000);return()=>{cancelled=true;obs.disconnect();clearTimeout(t)}}return()=>{cancelled=true}},[pathname]);
 async function run(opportunityId:string,operation:"PREVIEW"|"PUBLISH"){
  const c=currentCampaign();if(!c.name||!c.productSkus.length){setMessage("Select at least one campaign product and make sure the campaign has a name first.");return}if(operation==="PUBLISH"&&!c.campaignId){setMessage("Save this campaign once before publishing so LMG Marketing can retain the live page URL with the campaign.");return}if(operation==="PUBLISH"&&!confirm(`Publish/update the ${opportunityId==="landing-page"?"campaign landing page":"campaign collection page"} on Laughing Moose Gifts now?`))return;
  setBusy(`${operation}:${opportunityId}`);setMessage("");try{const r=await fetch("/api/integrations/woocommerce/campaign-pages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation,opportunityId,campaignId:c.campaignId,campaignName:c.name,headline:c.headline,body:c.body,cta:c.cta,productSkus:c.productSkus,startAt:c.startAt,endAt:c.endAt})}),d=await r.json();if(!r.ok)throw new Error(d.error||"WooCommerce page operation failed");if(d.preview)setPreview(p=>({...p,[opportunityId]:d.preview}));if(operation==="PUBLISH")setMessage(`${d.preview?.label||"Campaign page"} ${d.result?.created?"published":"updated"}: ${d.result?.url||d.preview?.intendedUrl}`);else setMessage(`${d.preview.label} preview refreshed. Nothing has been published.`)}catch(e){setMessage(e instanceof Error?e.message:"WooCommerce page operation failed.")}finally{setBusy("")}
 }
 if(pathname!=="/campaigns"||!host)return null;const c=currentCampaign(),ops=c.opportunityIds;
 return <div style={{maxWidth:1112,width:"calc(100% - 56px)",margin:"0 auto",padding:"14px",border:"1px solid #ccd8c8",borderRadius:12,background:"#f8fbf7"}}><div style={{fontWeight:900,fontSize:15}}>WooCommerce Opportunity Workbench</div><p style={{margin:"6px 0 12px",fontSize:13}}>Preview first, then explicitly publish or update the same WordPress page. Publishing is idempotent by campaign slug, so later changes update the existing page rather than creating duplicates.</p>{ops.length===0?<p style={{fontSize:13}}>Select Dedicated Campaign Landing Page and/or Campaign Collection Page above to activate their controls.</p>:ops.map(id=>{const p=preview[id];const label=id==="landing-page"?"Dedicated Campaign Landing Page":"Campaign Collection Page";return <div key={id} style={{borderTop:"1px solid #dde6da",paddingTop:12,marginTop:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><strong>{label}</strong><div style={{display:"flex",gap:8}}><button type="button" onClick={()=>run(id,"PREVIEW")} disabled={!!busy}>{busy===`PREVIEW:${id}`?"Building…":"Preview"}</button><button type="button" className="primary-button" onClick={()=>run(id,"PUBLISH")} disabled={!!busy}>{busy===`PUBLISH:${id}`?"Publishing…":p?"Publish / Update":"Publish"}</button></div></div>{p&&<div style={{marginTop:10,padding:10,background:"white",borderRadius:10,border:"1px solid #e1e6df"}}>{p.imageUrl&&<img src={p.imageUrl} alt="" style={{width:140,maxHeight:90,objectFit:"cover",borderRadius:8,float:"right",marginLeft:12}}/>}<strong>{p.headline}</strong><p style={{margin:"5px 0",fontSize:13}}>{p.body}</p><small>{p.products.length} products · {p.intendedUrl}</small><div style={{clear:"both"}}/></div>}</div>})}{message&&<p style={{margin:"12px 0 0",fontSize:13,fontWeight:700}}>{message}</p>}</div>;
}
