import {NextRequest,NextResponse} from "next/server";
import {db} from "@/lib/db";
import {publishHomepageHero,restoreHomepageHero,type HomepageSnapshot} from "@/lib/wordpress-homepage";

type Target={slot:string;opportunityId:string;campaignName:string;headline:string;body:string;cta:string;destinationUrl:string;imageUrl:string;startAt:string;endAt:string};
type Result={publishedAt?:string;restoredAt?:string;skippedAt?:string;snapshot?:HomepageSnapshot;wordpress?:unknown;error?:string};
const parse=<T,>(s:string|null)=>{if(!s)return null;try{return JSON.parse(s) as T}catch{return null}};

export async function GET(req:NextRequest){const ua=req.headers.get("user-agent")||"";if(!ua.includes("vercel-cron")&&req.headers.get("x-lmg-internal")!==process.env.LMG_INTERNAL_SYNC_SECRET)return NextResponse.json({error:"Not authorized"},{status:401});const now=new Date();const actions=await db.action.findMany({where:{actionType:"WORDPRESS_HOMEPAGE_HERO",completed:false},include:{recommendation:true},orderBy:{createdAt:"asc"}});const events:any[]=[];for(const action of actions){const target=parse<Target>(action.executionTarget);if(!target)continue;const result=parse<Result>(action.resultSummary)||{};const start=new Date(target.startAt),end=new Date(target.endAt);try{if(now<start)continue;if(now>=start&&now<end&&!result.publishedAt){const pub=await publishHomepageHero({headline:target.headline,body:target.body,cta:target.cta,destinationUrl:target.destinationUrl,imageUrl:target.imageUrl});const next:Result={...result,publishedAt:pub.publishedAt,snapshot:{pageId:pub.pageId,coverIndex:pub.coverIndex,coverRaw:pub.previousCoverRaw,capturedAt:pub.publishedAt},wordpress:{pageId:pub.pageId,mediaId:pub.mediaId,imageUrl:pub.imageUrl,verified:pub.verified}};await db.action.update({where:{id:action.id},data:{resultSummary:JSON.stringify(next)}});events.push({id:action.id,event:"PUBLISHED",campaign:target.campaignName});continue;}if(now>=end){if(result.publishedAt&&result.snapshot&&!result.restoredAt){const restored=await restoreHomepageHero(result.snapshot);const next:Result={...result,restoredAt:restored.restoredAt};await db.action.update({where:{id:action.id},data:{resultSummary:JSON.stringify(next),completed:true,completedAt:new Date()}});await db.recommendation.update({where:{id:action.recommendationId},data:{status:"EXECUTED",executedAt:new Date()}});events.push({id:action.id,event:"RESTORED",campaign:target.campaignName});}else if(!result.publishedAt){const next:Result={...result,skippedAt:new Date().toISOString(),error:"Scheduling window expired before publication executor ran."};await db.action.update({where:{id:action.id},data:{resultSummary:JSON.stringify(next),completed:true,completedAt:new Date()}});events.push({id:action.id,event:"MISSED",campaign:target.campaignName});}}}catch(e){const next:Result={...result,error:e instanceof Error?e.message:"WordPress execution failed"};await db.action.update({where:{id:action.id},data:{resultSummary:JSON.stringify(next)}});events.push({id:action.id,event:"ERROR",campaign:target.campaignName,error:next.error});}}
return NextResponse.json({ok:true,checked:actions.length,events,executedAt:new Date().toISOString()});}
