import { walmartRequest } from "./client";

export type ProductHealth="GREEN"|"YELLOW"|"RED";
export type ProductFinding={layer:string;severity:"WARNING"|"CRITICAL"|"WATCH";title:string;observation:string;likelyCause:string;recommendation:string;confidence:number};
type PricingResponse={data?:{pricingInsightsResponseList?:Array<any>}};
type Lookup={sku:string;item:any|null;pricing:any|null};

const normalize=(v:string)=>v.toUpperCase().replace(/[^A-Z0-9]/g,"");
function candidates(input:string){const clean=input.trim();const out=[clean];if(/^LMG/i.test(clean))out.push(clean.replace(/^LMG[-_ ]?/i,""));else out.push(`LMG${clean}`);return [...new Set(out.filter(Boolean))];}
function num(v:any):number|null{if(v==null)return null;if(typeof v==="number")return Number.isFinite(v)?v:null;if(typeof v==="string"){const n=Number(v.replace(/[^0-9.-]/g,""));return Number.isFinite(n)?n:null;}if(typeof v==="object")return num(v.amount??v.value??v.quantity??v.availToSellQty);return null;}
function inventoryQty(v:any):number|null{if(!v)return null;const direct=num(v.quantity??v.availToSellQty??v.inventoryCount??v.amount);if(direct!=null)return direct;const nodes=v.nodes??v.shipNodes??v.inventories??v.inventory;if(Array.isArray(nodes)){let seen=false,total=0;for(const n of nodes){const q=num(n?.availToSellQty??n?.quantity??n?.amount);if(q!=null){seen=true;total+=q;}}return seen?total:null;}return null;}
function expectedProductTypeHint(name:string):string|null{const n=name.toUpperCase();if(n.includes("CENTERPIECE"))return"Centerpieces";if(n.includes("POT HOLDER")||n.includes("POTHOLDER"))return"Pot Holders";if(n.includes("CANDLE"))return"Candles";if(n.includes("BLANKET")||n.includes("THROW"))return"Blankets & Throws";if(n.includes("TABLE RUNNER"))return"Table Runners";return null;}
function productTypeLooksCompatible(current:string|null,expected:string|null){if(!current||!expected)return null;const c=normalize(current);const e=normalize(expected);const stems=e.endsWith("S")?[e,e.slice(0,-1)]:[e];return stems.some(s=>c.includes(s)||s.includes(c));}
function targetTraffic(){return[1,2,3,4,5].map(rate=>({conversionRatePct:rate,minDailyVisits:Math.ceil(4/(rate/100)),maxDailyVisits:Math.ceil(6/(rate/100))}));}

async function getPricing(sku:string){try{const r=await walmartRequest<PricingResponse>("/v3/price/getPricingInsights",{method:"POST",body:JSON.stringify({pageNumber:0,searchCriteria:{searchField:"SKU",searchValue:[sku]}})});return r.data?.pricingInsightsResponseList?.[0]??null;}catch{return null;}}
async function getInventory(sku:string){try{return await walmartRequest<any>(`/v3/inventory?sku=${encodeURIComponent(sku)}`);}catch{try{return await walmartRequest<any>(`/v3/inventories/${encodeURIComponent(sku)}`);}catch{return null;}}}
async function trySku(sku:string):Promise<Lookup>{const[itemResult,pricing]=await Promise.all([walmartRequest<any>(`/v3/items/${encodeURIComponent(sku)}?productIdType=SKU`).catch(()=>null),getPricing(sku)]);return{sku,item:itemResult,pricing};}
async function resolveByCatalog(input:string):Promise<string|null>{const target=normalize(input.replace(/^LMG/i,""));for(let offset=0;offset<1000;offset+=50){const response=await walmartRequest<any>(`/v3/items?limit=50&offset=${offset}`);const rows=Array.isArray(response?.ItemResponse)?response.ItemResponse:[];for(const row of rows){const candidate=String(row?.sku??"");const n=normalize(candidate);if(n===normalize(input)||n===target||normalize(candidate.replace(/^LMG/i,""))===target)return candidate;}const total=Number(response?.totalItems??0);if(rows.length===0||(total&&offset+rows.length>=total))break;}return null;}

export async function diagnoseWalmartProduct(sku:string){
 const clean=sku.trim();if(!clean)throw new Error("SKU is required.");let lookup:Lookup|null=null;
 for(const candidate of candidates(clean)){const result=await trySku(candidate);if(result.item||result.pricing){lookup=result;break;}}
 if(!lookup){const resolved=await resolveByCatalog(clean);if(resolved)lookup=await trySku(resolved);}
 if(!lookup||(!lookup.item&&!lookup.pricing))throw new Error(`Walmart could not resolve ${clean} to a marketplace SKU. Try the Walmart SKU, UPC, or WPID shown in Seller Center.`);
 const resolvedSku=lookup.sku;const root=lookup.item?.ItemResponse?.[0]??lookup.item?.items?.[0]??lookup.item?.item??lookup.item;let pricing=lookup.pricing;if(!pricing)pricing=await getPricing(resolvedSku);
 const inventoryRaw=await getInventory(resolvedSku);const inventory=inventoryQty(inventoryRaw)??num(pricing?.inventoryCount)??num(root?.inventoryCount);
 const publish=String(root?.publishedStatus??root?.publishedStatusName??root?.lifecycleStatus??pricing?.itemPublishStatus??"UNKNOWN").toUpperCase();
 const name=String(pricing?.itemName??root?.productName??root?.itemName??resolvedSku);
 const productTypeRaw=root?.productType??root?.productTypeName??root?.itemType??root?.categoryPath?.productType??pricing?.productType??null;
 const productType=productTypeRaw==null?null:String(typeof productTypeRaw==="object"?(productTypeRaw.name??productTypeRaw.value??JSON.stringify(productTypeRaw)):productTypeRaw);
 const expectedProductType=expectedProductTypeHint(name);const productTypeCompatible=productTypeLooksCompatible(productType,expectedProductType);
 const buyBox=num(pricing?.buyBoxWinRate);const traffic=pricing?.traffic??null;const competitive=pricing?.priceCompetitive==null?null:Boolean(pricing.priceCompetitive);const currentPrice=num(pricing?.currentPrice??root?.price?.amount);const suggestedPrice=num(pricing?.suggestedPrice);const gmv30=num(pricing?.gmv30??pricing?.gmvL30D);const fulfillment=pricing?.fulfillment??root?.fulfillmentType??null;
 const findings:ProductFinding[]=[];
 if(!publish.includes("PUBLISH"))findings.push({layer:"CATALOG_HEALTH",severity:"CRITICAL",title:"Item is not clearly published",observation:`Walmart publish/lifecycle state is ${publish}.`,likelyCause:"Catalog validation, lifecycle, inventory, compliance, or publishing restrictions may be preventing normal exposure.",recommendation:"Inspect Walmart item errors and listing-quality issues before changing price or advertising.",confidence:.92});
 if(productTypeCompatible===false)findings.push({layer:"PRODUCT_TYPE",severity:"CRITICAL",title:"Product Type appears inconsistent with the item",observation:`Walmart Product Type is ${productType}; the item title strongly indicates ${expectedProductType}.`,likelyCause:"Walmart taxonomy/PIA classification is likely placing the item in the wrong product type, which can impair required attributes, indexing, filters and search retrieval.",recommendation:`Treat Product Type correction as a priority. Preserve evidence that this is a ${expectedProductType} item, submit/maintain the correct taxonomy attributes, and do not let automated maintenance overwrite the corrected Product Type.`,confidence:.96});
 else if(!productType)findings.push({layer:"PRODUCT_TYPE",severity:"WATCH",title:"Product Type evidence is missing",observation:"The live item response did not expose a Product Type value.",likelyCause:"The current item endpoint response is not surfacing taxonomy detail for this SKU.",recommendation:"Retrieve Product Type through Walmart taxonomy/search-insights evidence before declaring catalog health complete.",confidence:1});
 if(inventory!=null&&inventory<=0)findings.push({layer:"INVENTORY",severity:"CRITICAL",title:"Item is out of stock",observation:"Available inventory is zero.",likelyCause:"The offer cannot transact and may disappear from search exposure.",recommendation:"Replenish or correct Walmart inventory before other optimization work.",confidence:.99});else if(inventory!=null&&inventory<=3)findings.push({layer:"INVENTORY",severity:"WARNING",title:"Inventory is very low",observation:`Only ${inventory} units are available.`,likelyCause:"Low stock can limit transactability and creates imminent lost-sales risk.",recommendation:"Replenish inventory and verify fulfillment-node quantities.",confidence:.95});
 if(buyBox!=null&&buyBox<50)findings.push({layer:"OFFER",severity:buyBox<10?"CRITICAL":"WARNING",title:"Weak Buy Box performance",observation:`Buy Box win rate is ${buyBox.toFixed(1)}%.`,likelyCause:"Price, shipping promise, fulfillment or competing offers are limiting ownership of the offer.",recommendation:"Compare current total price, Walmart Buy Box price, competitor price, suggested price and fulfillment promise before approving an offer change.",confidence:.94});
 if(competitive===false)findings.push({layer:"OFFER",severity:"WARNING",title:"Price is not competitive",observation:`Current price ${currentPrice==null?"is available":`is $${currentPrice.toFixed(2)}`}${suggestedPrice==null?"":`; Walmart suggested price is $${suggestedPrice.toFixed(2)}`}.`,likelyCause:"Walmart sees a recoverable pricing competitiveness gap.",recommendation:"Model margin impact of Walmart's suggested/competitive price and only change price after approval.",confidence:.96});
 if(traffic==="LOW"||traffic==="VERY_LOW")findings.push({layer:"VISIBILITY",severity:traffic==="VERY_LOW"?"WARNING":"WATCH",title:"Low Walmart traffic",observation:`Pricing Insights classifies traffic as ${traffic}. Walmart does not expose the visit count in this field.`,likelyCause:buyBox!=null&&buyBox<50?"Offer competitiveness/Buy Box loss may be suppressing effective exposure; discoverability may also contribute.":productTypeCompatible===false?"Incorrect Product Type is a strong candidate for poor discoverability, along with title/attribute/keyword coverage.":"Search discoverability, taxonomy, attributes, title/content, demand, or keyword coverage may be limiting exposure.",recommendation:"Use Item Performance to obtain actual product visits and conversion. For a 4–6 unit/day target, compare actual visits with the target-traffic table shown in the workbench.",confidence:.88});
 if(gmv30===0&&(!traffic||traffic==="LOW"||traffic==="VERY_LOW"))findings.push({layer:"DEMAND",severity:"WATCH",title:"No recent GMV signal",observation:"Pricing Insights shows no 30-day GMV for this SKU.",likelyCause:"The item may have insufficient exposure, weak conversion, or limited recent demand.",recommendation:"Use Item Performance history to separate a traffic problem from a conversion problem before changing content or price.",confidence:.72});
 const missing=[inventory==null?"inventory":null,buyBox==null?"Buy Box":null,competitive==null?"price competitiveness":null,traffic==null?"traffic":null,gmv30==null?"30-day GMV":null,productType==null?"Product Type":null].filter(Boolean) as string[];
 if(missing.length)findings.push({layer:"DATA_GAP",severity:"WATCH",title:"Walmart evidence is incomplete",observation:`Missing live evidence: ${missing.join(", ")}.`,likelyCause:"Walmart did not return all product-level telemetry for this SKU in the live endpoints.",recommendation:"Do not classify this product as healthy yet. Refresh Pricing Insights and use Item Performance/Search Insights to fill the remaining evidence gaps.",confidence:1});
 const health:ProductHealth=findings.some(f=>f.severity==="CRITICAL")?"RED":findings.length?"YELLOW":"GREEN";
 return{requestedSku:clean,sku:resolvedSku,resolvedSku:resolvedSku!==clean?resolvedSku:null,name,health,summary:{publishStatus:publish,productType,expectedProductType,productTypeCompatible,inventory,buyBoxWinRate:buyBox,traffic,priceCompetitive:competitive,currentPrice,suggestedPrice,fulfillment,gmv30},salesTarget:{minUnitsPerDay:4,maxUnitsPerDay:6,trafficByConversion:targetTraffic()},findings,evidenceGaps:{searchInsights:true,itemPerformance:true,liveFields:missing},nextEvidence:"Use Item Performance for exact visits/conversion and Search Insights for impressions, clicks, ranks, keywords and Product Type context."};
}
